/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lexico;

import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author Cleverton
 */
public class TabelaDeTransicao {
    
    private ArrayList<HashMap> T;
    private HashMap<Integer, String> ts ;
    private HashMap<String, String> pReservada ;
    
    public TabelaDeTransicao(){
        T = new ArrayList();
        ts = new HashMap();
        pReservada = new HashMap();
        this.constroiTabela();
        this.constroiTabelaTokens();
        this.palavrasReservadas();
    }

    public ArrayList<HashMap> getT() {
        return T;
    }

    public void setT(ArrayList<HashMap> T) {
        this.T = T;
    }

    public HashMap<Integer, String> getTs() {
        return ts;
    }

    public HashMap<String, String> getpReservada() {
        return pReservada;
    }

    public void setpReservada(HashMap<String, String> pReservada) {
        this.pReservada = pReservada;
    }
    
    public void constroiTabela(){
        HashMap<String, Integer> h2 = new HashMap(); 
       
        //ESTADO 0 - ?
        h2.put("\t", 1);
        h2.put("\n", 1);
        h2.put("\r", 1);
        h2.put(" ",  1);
        h2.put("!",  2);
        h2.put("\"",-1);
        h2.put("#", -1);
        h2.put("$", -1);
        h2.put("%", -1);
        h2.put("&",  3);
        h2.put("´", -1);
        h2.put("(",  4);
        h2.put(")",  5);
        h2.put("*",  6);
        h2.put("+",  7);
        h2.put(",",  8);
        h2.put("-",  9);
        h2.put(".", -1);
        h2.put("/", 10);
        h2.put("0", 11);
        h2.put("1", 11);
        h2.put("2", 11);
        h2.put("3", 11);
        h2.put("4", 11);
        h2.put("5", 11);
        h2.put("6", 11);
        h2.put("7", 11);
        h2.put("8", 11);
        h2.put("9", 11);
        h2.put(":", 12);
        h2.put(";", 13);
        h2.put("<", 14);
        h2.put("=", 15);
        h2.put(">", 16);
        h2.put("?", -1);
        h2.put("@", -1);
        h2.put("A", 17);
        h2.put("B", 17);
        h2.put("C", 17);
        h2.put("D", 17);
        h2.put("E", 17);
        h2.put("F", 17);
        h2.put("G", 17);
        h2.put("H", 17);
        h2.put("I", 17);
        h2.put("J", 17);
        h2.put("K", 17);
        h2.put("L", 17);
        h2.put("M", 17);
        h2.put("N", 17);
        h2.put("O", 17);
        h2.put("P", 17);
        h2.put("Q", 17);
        h2.put("R", 17);
        h2.put("S", 17);
        h2.put("T", 17);
        h2.put("U", 17);
        h2.put("V", 17);
        h2.put("X", 17);
        h2.put("W", 17);
        h2.put("Y", 17);
        h2.put("X", 17);
        h2.put("Z", 17);
        h2.put("[", -1);
        h2.put("\'",-1);
        h2.put("]", -1);
        h2.put("^", -1);
        h2.put("_", -1);
        h2.put("`", -1);
        h2.put("a", 17);
        h2.put("b", 17);
        h2.put("c", 17);
        h2.put("d", 17);
        h2.put("e", 17);
        h2.put("f", 17);
        h2.put("g", 17);
        h2.put("h", 17);
        h2.put("i", 17);
        h2.put("j", 17);
        h2.put("k", 17);
        h2.put("l", 17);
        h2.put("m", 17);
        h2.put("n", 17);
        h2.put("o", 17);
        h2.put("p", 17);
        h2.put("q", 17);
        h2.put("r", 17);
        h2.put("s", 17);
        h2.put("t", 17);
        h2.put("u", 17);
        h2.put("v", 17);
        h2.put("w", 17);
        h2.put("x", 17);
        h2.put("y", 17);
        h2.put("z", 17);
        h2.put("{", 18);
        h2.put("|", 19);
        h2.put("}", 20);  
        T.add(h2);
        
        //ESTADO 1 - :-ESPAÇO
        h2 = new HashMap();
        h2.put("\t",-1);
        h2.put("\n",-1);
        h2.put("\r",-1);
        h2.put(" ", -1);
        h2.put("!", -1);
        h2.put("\"",-1);
        h2.put("#", -1);
        h2.put("$", -1);
        h2.put("%", -1);
        h2.put("&", -1);
        h2.put("´", -1);
        h2.put("(", -1);
        h2.put(")", -1);
        h2.put("*", -1);
        h2.put("+", -1);
        h2.put(",", -1);
        h2.put("-", -1);
        h2.put(".", -1);
        h2.put("/", -1);
        h2.put("0", -1);
        h2.put("1", -1);
        h2.put("2", -1);
        h2.put("3", -1);
        h2.put("4", -1);
        h2.put("5", -1);
        h2.put("6", -1);
        h2.put("7", -1);
        h2.put("8", -1);
        h2.put("9", -1);
        h2.put(":", -1);
        h2.put(";", -1);
        h2.put("<", -1);
        h2.put("=", -1);
        h2.put(">", -1);
        h2.put("?", -1);
        h2.put("@", -1);
        h2.put("A", -1);
        h2.put("B", -1);
        h2.put("C", -1);
        h2.put("D", -1);
        h2.put("E", -1);
        h2.put("F", -1);
        h2.put("G", -1);
        h2.put("H", -1);
        h2.put("I", -1);
        h2.put("J", -1);
        h2.put("K", -1);
        h2.put("L", -1);
        h2.put("M", -1);
        h2.put("N", -1);
        h2.put("O", -1);
        h2.put("P", -1);
        h2.put("Q", -1);
        h2.put("R", -1);
        h2.put("S", -1);
        h2.put("T", -1);
        h2.put("U", -1);
        h2.put("V", -1);
        h2.put("X", -1);
        h2.put("W", -1);
        h2.put("Y", -1);
        h2.put("X", -1);
        h2.put("Z", -1);
        h2.put("[", -1);
        h2.put("\'",-1);
        h2.put("]", -1);
        h2.put("^", -1);
        h2.put("_", -1);
        h2.put("`", -1);
        h2.put("a", -1);
        h2.put("b", -1);
        h2.put("c", -1);
        h2.put("d", -1);
        h2.put("e", -1);
        h2.put("f", -1);
        h2.put("g", -1);
        h2.put("h", -1);
        h2.put("i", -1);
        h2.put("j", -1);
        h2.put("k", -1);
        h2.put("l", -1);
        h2.put("m", -1);
        h2.put("n", -1);
        h2.put("o", -1);
        h2.put("p", -1);
        h2.put("q", -1);
        h2.put("r", -1);
        h2.put("s", -1);
        h2.put("t", -1);
        h2.put("u", -1);
        h2.put("v", -1);
        h2.put("w", -1);
        h2.put("x", -1);
        h2.put("y", -1);
        h2.put("z", -1);
        h2.put("{", -1);
        h2.put("|", -1);
        h2.put("}", -1);  
        T.add(h2);
        
        //ESTADO 2 - not
        h2 = new HashMap();
        h2.put("\t",-1);
        h2.put("\n",-1);
        h2.put("\r",-1);
        h2.put(" ", -1);
        h2.put("!", -1);
        h2.put("\"",-1);
        h2.put("#", -1);
        h2.put("$", -1);
        h2.put("%", -1);
        h2.put("&", -1);
        h2.put("´", -1);
        h2.put("(", -1);
        h2.put(")", -1);
        h2.put("*", -1);
        h2.put("+", -1);
        h2.put(",", -1);
        h2.put("-", -1);
        h2.put(".", -1);
        h2.put("/", -1);
        h2.put("0", -1);
        h2.put("1", -1);
        h2.put("2", -1);
        h2.put("3", -1);
        h2.put("4", -1);
        h2.put("5", -1);
        h2.put("6", -1);
        h2.put("7", -1);
        h2.put("8", -1);
        h2.put("9", -1);
        h2.put(":", -1);
        h2.put(";", -1);
        h2.put("<", -1);
        h2.put("=", -1);
        h2.put(">", -1);
        h2.put("?", -1);
        h2.put("@", -1);
        h2.put("A", -1);
        h2.put("B", -1);
        h2.put("C", -1);
        h2.put("D", -1);
        h2.put("E", -1);
        h2.put("F", -1);
        h2.put("G", -1);
        h2.put("H", -1);
        h2.put("I", -1);
        h2.put("J", -1);
        h2.put("K", -1);
        h2.put("L", -1);
        h2.put("M", -1);
        h2.put("N", -1);
        h2.put("O", -1);
        h2.put("P", -1);
        h2.put("Q", -1);
        h2.put("R", -1);
        h2.put("S", -1);
        h2.put("T", -1);
        h2.put("U", -1);
        h2.put("V", -1);
        h2.put("X", -1);
        h2.put("W", -1);
        h2.put("Y", -1);
        h2.put("X", -1);
        h2.put("Z", -1);
        h2.put("[", -1);
        h2.put("\'",-1);
        h2.put("]", -1);
        h2.put("^", -1);
        h2.put("_", -1);
        h2.put("`", -1);
        h2.put("a", -1);
        h2.put("b", -1);
        h2.put("c", -1);
        h2.put("d", -1);
        h2.put("e", -1);
        h2.put("f", -1);
        h2.put("g", -1);
        h2.put("h", -1);
        h2.put("i", -1);
        h2.put("j", -1);
        h2.put("k", -1);
        h2.put("l", -1);
        h2.put("m", -1);
        h2.put("n", -1);
        h2.put("o", -1);
        h2.put("p", -1);
        h2.put("q", -1);
        h2.put("r", -1);
        h2.put("s", -1);
        h2.put("t", -1);
        h2.put("u", -1);
        h2.put("v", -1);
        h2.put("w", -1);
        h2.put("x", -1);
        h2.put("y", -1);
        h2.put("z", -1);
        h2.put("{", -1);
        h2.put("|", -1);
        h2.put("}", -1);  
        T.add(h2);  
        
        //ESTADO 3 - ?
        h2 = new HashMap();
        h2.put("\t",-1);
        h2.put("\n",-1);
        h2.put("\r",-1);
        h2.put(" ", -1);
        h2.put("!", -1);
        h2.put("\"",-1);
        h2.put("#", -1);
        h2.put("$", -1);
        h2.put("%", -1);
        h2.put("&", 21);
        h2.put("´", -1);
        h2.put("(", -1);
        h2.put(")", -1);
        h2.put("*", -1);
        h2.put("+", -1);
        h2.put(",", -1);
        h2.put("-", -1);
        h2.put(".", -1);
        h2.put("/", -1);
        h2.put("0", -1);
        h2.put("1", -1);
        h2.put("2", -1);
        h2.put("3", -1);
        h2.put("4", -1);
        h2.put("5", -1);
        h2.put("6", -1);
        h2.put("7", -1);
        h2.put("8", -1);
        h2.put("9", -1);
        h2.put(":", -1);
        h2.put(";", -1);
        h2.put("<", -1);
        h2.put("=", -1);
        h2.put(">", -1);
        h2.put("?", -1);
        h2.put("@", -1);
        h2.put("A", -1);
        h2.put("B", -1);
        h2.put("C", -1);
        h2.put("D", -1);
        h2.put("E", -1);
        h2.put("F", -1);
        h2.put("G", -1);
        h2.put("H", -1);
        h2.put("I", -1);
        h2.put("J", -1);
        h2.put("K", -1);
        h2.put("L", -1);
        h2.put("M", -1);
        h2.put("N", -1);
        h2.put("O", -1);
        h2.put("P", -1);
        h2.put("Q", -1);
        h2.put("R", -1);
        h2.put("S", -1);
        h2.put("T", -1);
        h2.put("U", -1);
        h2.put("V", -1);
        h2.put("X", -1);
        h2.put("W", -1);
        h2.put("Y", -1);
        h2.put("X", -1);
        h2.put("Z", -1);
        h2.put("[", -1);
        h2.put("\'",-1);
        h2.put("]", -1);
        h2.put("^", -1);
        h2.put("_", -1);
        h2.put("`", -1);
        h2.put("a", -1);
        h2.put("b", -1);
        h2.put("c", -1);
        h2.put("d", -1);
        h2.put("e", -1);
        h2.put("f", -1);
        h2.put("g", -1);
        h2.put("h", -1);
        h2.put("i", -1);
        h2.put("j", -1);
        h2.put("k", -1);
        h2.put("l", -1);
        h2.put("m", -1);
        h2.put("n", -1);
        h2.put("o", -1);
        h2.put("p", -1);
        h2.put("q", -1);
        h2.put("r", -1);
        h2.put("s", -1);
        h2.put("t", -1);
        h2.put("u", -1);
        h2.put("v", -1);
        h2.put("w", -1);
        h2.put("x", -1);
        h2.put("y", -1);
        h2.put("z", -1);
        h2.put("{", -1);
        h2.put("|", -1);
        h2.put("}", -1);  
        T.add(h2);
        
        //ESTADO 4 - ap
        h2 = new HashMap();
        h2.put("\t",-1);
        h2.put("\n",-1);
        h2.put("\r",-1);
        h2.put(" ", -1);
        h2.put("!", -1);
        h2.put("\"",-1);
        h2.put("#", -1);
        h2.put("$", -1);
        h2.put("%", -1);
        h2.put("&", -1);
        h2.put("´", -1);
        h2.put("(", -1);
        h2.put(")", -1);
        h2.put("*", -1);
        h2.put("+", -1);
        h2.put(",", -1);
        h2.put("-", -1);
        h2.put(".", -1);
        h2.put("/", -1);
        h2.put("0", -1);
        h2.put("1", -1);
        h2.put("2", -1);
        h2.put("3", -1);
        h2.put("4", -1);
        h2.put("5", -1);
        h2.put("6", -1);
        h2.put("7", -1);
        h2.put("8", -1);
        h2.put("9", -1);
        h2.put(":", -1);
        h2.put(";", -1);
        h2.put("<", -1);
        h2.put("=", -1);
        h2.put(">", -1);
        h2.put("?", -1);
        h2.put("@", -1);
        h2.put("A", -1);
        h2.put("B", -1);
        h2.put("C", -1);
        h2.put("D", -1);
        h2.put("E", -1);
        h2.put("F", -1);
        h2.put("G", -1);
        h2.put("H", -1);
        h2.put("I", -1);
        h2.put("J", -1);
        h2.put("K", -1);
        h2.put("L", -1);
        h2.put("M", -1);
        h2.put("N", -1);
        h2.put("O", -1);
        h2.put("P", -1);
        h2.put("Q", -1);
        h2.put("R", -1);
        h2.put("S", -1);
        h2.put("T", -1);
        h2.put("U", -1);
        h2.put("V", -1);
        h2.put("X", -1);
        h2.put("W", -1);
        h2.put("Y", -1);
        h2.put("X", -1);
        h2.put("Z", -1);
        h2.put("[", -1);
        h2.put("\'",-1);
        h2.put("]", -1);
        h2.put("^", -1);
        h2.put("_", -1);
        h2.put("`", -1);
        h2.put("a", -1);
        h2.put("b", -1);
        h2.put("c", -1);
        h2.put("d", -1);
        h2.put("e", -1);
        h2.put("f", -1);
        h2.put("g", -1);
        h2.put("h", -1);
        h2.put("i", -1);
        h2.put("j", -1);
        h2.put("k", -1);
        h2.put("l", -1);
        h2.put("m", -1);
        h2.put("n", -1);
        h2.put("o", -1);
        h2.put("p", -1);
        h2.put("q", -1);
        h2.put("r", -1);
        h2.put("s", -1);
        h2.put("t", -1);
        h2.put("u", -1);
        h2.put("v", -1);
        h2.put("w", -1);
        h2.put("x", -1);
        h2.put("y", -1);
        h2.put("z", -1);
        h2.put("{", -1);
        h2.put("|", -1);
        h2.put("}", -1);  
        T.add(h2);
        
        //ESTADO 5 - fp
        h2 = new HashMap();
        h2.put("\t",-1);
        h2.put("\n",-1);
        h2.put("\r",-1);
        h2.put(" ", -1);
        h2.put("!", -1);
        h2.put("\"",-1);
        h2.put("#", -1);
        h2.put("$", -1);
        h2.put("%", -1);
        h2.put("&", -1);
        h2.put("´", -1);
        h2.put("(", -1);
        h2.put(")", -1);
        h2.put("*", -1);
        h2.put("+", -1);
        h2.put(",", -1);
        h2.put("-", -1);
        h2.put(".", -1);
        h2.put("/", -1);
        h2.put("0", -1);
        h2.put("1", -1);
        h2.put("2", -1);
        h2.put("3", -1);
        h2.put("4", -1);
        h2.put("5", -1);
        h2.put("6", -1);
        h2.put("7", -1);
        h2.put("8", -1);
        h2.put("9", -1);
        h2.put(":", -1);
        h2.put(";", -1);
        h2.put("<", -1);
        h2.put("=", -1);
        h2.put(">", -1);
        h2.put("?", -1);
        h2.put("@", -1);
        h2.put("A", -1);
        h2.put("B", -1);
        h2.put("C", -1);
        h2.put("D", -1);
        h2.put("E", -1);
        h2.put("F", -1);
        h2.put("G", -1);
        h2.put("H", -1);
        h2.put("I", -1);
        h2.put("J", -1);
        h2.put("K", -1);
        h2.put("L", -1);
        h2.put("M", -1);
        h2.put("N", -1);
        h2.put("O", -1);
        h2.put("P", -1);
        h2.put("Q", -1);
        h2.put("R", -1);
        h2.put("S", -1);
        h2.put("T", -1);
        h2.put("U", -1);
        h2.put("V", -1);
        h2.put("X", -1);
        h2.put("W", -1);
        h2.put("Y", -1);
        h2.put("X", -1);
        h2.put("Z", -1);
        h2.put("[", -1);
        h2.put("\'",-1);
        h2.put("]", -1);
        h2.put("^", -1);
        h2.put("_", -1);
        h2.put("`", -1);
        h2.put("a", -1);
        h2.put("b", -1);
        h2.put("c", -1);
        h2.put("d", -1);
        h2.put("e", -1);
        h2.put("f", -1);
        h2.put("g", -1);
        h2.put("h", -1);
        h2.put("i", -1);
        h2.put("j", -1);
        h2.put("k", -1);
        h2.put("l", -1);
        h2.put("m", -1);
        h2.put("n", -1);
        h2.put("o", -1);
        h2.put("p", -1);
        h2.put("q", -1);
        h2.put("r", -1);
        h2.put("s", -1);
        h2.put("t", -1);
        h2.put("u", -1);
        h2.put("v", -1);
        h2.put("w", -1);
        h2.put("x", -1);
        h2.put("y", -1);
        h2.put("z", -1);
        h2.put("{", -1);
        h2.put("|", -1);
        h2.put("}", -1);  
        T.add(h2);
        
        //ESTADO 6 - mult
        h2 = new HashMap();
        h2.put("\t",-1);
        h2.put("\n",-1);
        h2.put("\r",-1);
        h2.put(" ", -1);
        h2.put("!", -1);
        h2.put("\"",-1);
        h2.put("#", -1);
        h2.put("$", -1);
        h2.put("%", -1);
        h2.put("&", -1);
        h2.put("´", -1);
        h2.put("(", -1);
        h2.put(")", -1);
        h2.put("*", -1);
        h2.put("+", -1);
        h2.put(",", -1);
        h2.put("-", -1);
        h2.put(".", -1);
        h2.put("/", -1);
        h2.put("0", -1);
        h2.put("1", -1);
        h2.put("2", -1);
        h2.put("3", -1);
        h2.put("4", -1);
        h2.put("5", -1);
        h2.put("6", -1);
        h2.put("7", -1);
        h2.put("8", -1);
        h2.put("9", -1);
        h2.put(":", -1);
        h2.put(";", -1);
        h2.put("<", -1);
        h2.put("=", -1);
        h2.put(">", -1);
        h2.put("?", -1);
        h2.put("@", -1);
        h2.put("A", -1);
        h2.put("B", -1);
        h2.put("C", -1);
        h2.put("D", -1);
        h2.put("E", -1);
        h2.put("F", -1);
        h2.put("G", -1);
        h2.put("H", -1);
        h2.put("I", -1);
        h2.put("J", -1);
        h2.put("K", -1);
        h2.put("L", -1);
        h2.put("M", -1);
        h2.put("N", -1);
        h2.put("O", -1);
        h2.put("P", -1);
        h2.put("Q", -1);
        h2.put("R", -1);
        h2.put("S", -1);
        h2.put("T", -1);
        h2.put("U", -1);
        h2.put("V", -1);
        h2.put("X", -1);
        h2.put("W", -1);
        h2.put("Y", -1);
        h2.put("X", -1);
        h2.put("Z", -1);
        h2.put("[", -1);
        h2.put("\'",-1);
        h2.put("]", -1);
        h2.put("^", -1);
        h2.put("_", -1);
        h2.put("`", -1);
        h2.put("a", -1);
        h2.put("b", -1);
        h2.put("c", -1);
        h2.put("d", -1);
        h2.put("e", -1);
        h2.put("f", -1);
        h2.put("g", -1);
        h2.put("h", -1);
        h2.put("i", -1);
        h2.put("j", -1);
        h2.put("k", -1);
        h2.put("l", -1);
        h2.put("m", -1);
        h2.put("n", -1);
        h2.put("o", -1);
        h2.put("p", -1);
        h2.put("q", -1);
        h2.put("r", -1);
        h2.put("s", -1);
        h2.put("t", -1);
        h2.put("u", -1);
        h2.put("v", -1);
        h2.put("w", -1);
        h2.put("x", -1);
        h2.put("y", -1);
        h2.put("z", -1);
        h2.put("{", -1);
        h2.put("|", -1);
        h2.put("}", -1);  
        T.add(h2);
        
        //ESTADO 7 - soma
        h2 = new HashMap();
        h2.put("\t",-1);
        h2.put("\n",-1);
        h2.put("\r",-1);
        h2.put(" ", -1);
        h2.put("!", -1);
        h2.put("\"",-1);
        h2.put("#", -1);
        h2.put("$", -1);
        h2.put("%", -1);
        h2.put("&", -1);
        h2.put("´", -1);
        h2.put("(", -1);
        h2.put(")", -1);
        h2.put("*", -1);
        h2.put("+", 22);
        h2.put(",", -1);
        h2.put("-", -1);
        h2.put(".", -1);
        h2.put("/", -1);
        h2.put("0", -1);
        h2.put("1", -1);
        h2.put("2", -1);
        h2.put("3", -1);
        h2.put("4", -1);
        h2.put("5", -1);
        h2.put("6", -1);
        h2.put("7", -1);
        h2.put("8", -1);
        h2.put("9", -1);
        h2.put(":", -1);
        h2.put(";", -1);
        h2.put("<", -1);
        h2.put("=", -1);
        h2.put(">", -1);
        h2.put("?", -1);
        h2.put("@", -1);
        h2.put("A", -1);
        h2.put("B", -1);
        h2.put("C", -1);
        h2.put("D", -1);
        h2.put("E", -1);
        h2.put("F", -1);
        h2.put("G", -1);
        h2.put("H", -1);
        h2.put("I", -1);
        h2.put("J", -1);
        h2.put("K", -1);
        h2.put("L", -1);
        h2.put("M", -1);
        h2.put("N", -1);
        h2.put("O", -1);
        h2.put("P", -1);
        h2.put("Q", -1);
        h2.put("R", -1);
        h2.put("S", -1);
        h2.put("T", -1);
        h2.put("U", -1);
        h2.put("V", -1);
        h2.put("X", -1);
        h2.put("W", -1);
        h2.put("Y", -1);
        h2.put("X", -1);
        h2.put("Z", -1);
        h2.put("[", -1);
        h2.put("\'",-1);
        h2.put("]", -1);
        h2.put("^", -1);
        h2.put("_", -1);
        h2.put("`", -1);
        h2.put("a", -1);
        h2.put("b", -1);
        h2.put("c", -1);
        h2.put("d", -1);
        h2.put("e", -1);
        h2.put("f", -1);
        h2.put("g", -1);
        h2.put("h", -1);
        h2.put("i", -1);
        h2.put("j", -1);
        h2.put("k", -1);
        h2.put("l", -1);
        h2.put("m", -1);
        h2.put("n", -1);
        h2.put("o", -1);
        h2.put("p", -1);
        h2.put("q", -1);
        h2.put("r", -1);
        h2.put("s", -1);
        h2.put("t", -1);
        h2.put("u", -1);
        h2.put("v", -1);
        h2.put("w", -1);
        h2.put("x", -1);
        h2.put("y", -1);
        h2.put("z", -1);
        h2.put("{", -1);
        h2.put("|", -1);
        h2.put("}", -1);  
        T.add(h2);
        
        //ESTADO 8 - v
        h2 = new HashMap();
        h2.put("\t",-1);
        h2.put("\n",-1);
        h2.put("\r",-1);
        h2.put(" ", -1);
        h2.put("!", -1);
        h2.put("\"",-1);
        h2.put("#", -1);
        h2.put("$", -1);
        h2.put("%", -1);
        h2.put("&", -1);
        h2.put("´", -1);
        h2.put("(", -1);
        h2.put(")", -1);
        h2.put("*", -1);
        h2.put("+", -1);
        h2.put(",", -1);
        h2.put("-", -1);
        h2.put(".", -1);
        h2.put("/", -1);
        h2.put("0", -1);
        h2.put("1", -1);
        h2.put("2", -1);
        h2.put("3", -1);
        h2.put("4", -1);
        h2.put("5", -1);
        h2.put("6", -1);
        h2.put("7", -1);
        h2.put("8", -1);
        h2.put("9", -1);
        h2.put(":", -1);
        h2.put(";", -1);
        h2.put("<", -1);
        h2.put("=", -1);
        h2.put(">", -1);
        h2.put("?", -1);
        h2.put("@", -1);
        h2.put("A", -1);
        h2.put("B", -1);
        h2.put("C", -1);
        h2.put("D", -1);
        h2.put("E", -1);
        h2.put("F", -1);
        h2.put("G", -1);
        h2.put("H", -1);
        h2.put("I", -1);
        h2.put("J", -1);
        h2.put("K", -1);
        h2.put("L", -1);
        h2.put("M", -1);
        h2.put("N", -1);
        h2.put("O", -1);
        h2.put("P", -1);
        h2.put("Q", -1);
        h2.put("R", -1);
        h2.put("S", -1);
        h2.put("T", -1);
        h2.put("U", -1);
        h2.put("V", -1);
        h2.put("X", -1);
        h2.put("W", -1);
        h2.put("Y", -1);
        h2.put("X", -1);
        h2.put("Z", -1);
        h2.put("[", -1);
        h2.put("\'",-1);
        h2.put("]", -1);
        h2.put("^", -1);
        h2.put("_", -1);
        h2.put("`", -1);
        h2.put("a", -1);
        h2.put("b", -1);
        h2.put("c", -1);
        h2.put("d", -1);
        h2.put("e", -1);
        h2.put("f", -1);
        h2.put("g", -1);
        h2.put("h", -1);
        h2.put("i", -1);
        h2.put("j", -1);
        h2.put("k", -1);
        h2.put("l", -1);
        h2.put("m", -1);
        h2.put("n", -1);
        h2.put("o", -1);
        h2.put("p", -1);
        h2.put("q", -1);
        h2.put("r", -1);
        h2.put("s", -1);
        h2.put("t", -1);
        h2.put("u", -1);
        h2.put("v", -1);
        h2.put("w", -1);
        h2.put("x", -1);
        h2.put("y", -1);
        h2.put("z", -1);
        h2.put("{", -1);
        h2.put("|", -1);
        h2.put("}", -1);  
        T.add(h2);
        
        //ESTADO 9 - subt
        h2 = new HashMap();
        h2.put("\t",-1);
        h2.put("\n",-1);
        h2.put("\r",-1);
        h2.put(" ", -1);
        h2.put("!", -1);
        h2.put("\"",-1);
        h2.put("#", -1);
        h2.put("$", -1);
        h2.put("%", -1);
        h2.put("&", -1);
        h2.put("´", -1);
        h2.put("(", -1);
        h2.put(")", -1);
        h2.put("*", -1);
        h2.put("+", -1);
        h2.put(",", -1);
        h2.put("-", 23);
        h2.put(".", -1);
        h2.put("/", -1);
        h2.put("0", -1);
        h2.put("1", -1);
        h2.put("2", -1);
        h2.put("3", -1);
        h2.put("4", -1);
        h2.put("5", -1);
        h2.put("6", -1);
        h2.put("7", -1);
        h2.put("8", -1);
        h2.put("9", -1);
        h2.put(":", -1);
        h2.put(";", -1);
        h2.put("<", -1);
        h2.put("=", -1);
        h2.put(">", -1);
        h2.put("?", -1);
        h2.put("@", -1);
        h2.put("A", -1);
        h2.put("B", -1);
        h2.put("C", -1);
        h2.put("D", -1);
        h2.put("E", -1);
        h2.put("F", -1);
        h2.put("G", -1);
        h2.put("H", -1);
        h2.put("I", -1);
        h2.put("J", -1);
        h2.put("K", -1);
        h2.put("L", -1);
        h2.put("M", -1);
        h2.put("N", -1);
        h2.put("O", -1);
        h2.put("P", -1);
        h2.put("Q", -1);
        h2.put("R", -1);
        h2.put("S", -1);
        h2.put("T", -1);
        h2.put("U", -1);
        h2.put("V", -1);
        h2.put("X", -1);
        h2.put("W", -1);
        h2.put("Y", -1);
        h2.put("X", -1);
        h2.put("Z", -1);
        h2.put("[", -1);
        h2.put("\'",-1);
        h2.put("]", -1);
        h2.put("^", -1);
        h2.put("_", -1);
        h2.put("`", -1);
        h2.put("a", -1);
        h2.put("b", -1);
        h2.put("c", -1);
        h2.put("d", -1);
        h2.put("e", -1);
        h2.put("f", -1);
        h2.put("g", -1);
        h2.put("h", -1);
        h2.put("i", -1);
        h2.put("j", -1);
        h2.put("k", -1);
        h2.put("l", -1);
        h2.put("m", -1);
        h2.put("n", -1);
        h2.put("o", -1);
        h2.put("p", -1);
        h2.put("q", -1);
        h2.put("r", -1);
        h2.put("s", -1);
        h2.put("t", -1);
        h2.put("u", -1);
        h2.put("v", -1);
        h2.put("w", -1);
        h2.put("x", -1);
        h2.put("y", -1);
        h2.put("z", -1);
        h2.put("{", -1);
        h2.put("|", -1);
        h2.put("}", -1);  
        T.add(h2);
        
        //ESTADO 10 - div
        h2 = new HashMap();
        h2.put("\t",-1);
        h2.put("\n",-1);
        h2.put("\r",-1);
        h2.put(" ", -1);
        h2.put("!", -1);
        h2.put("\"",-1);
        h2.put("#", -1);
        h2.put("$", -1);
        h2.put("%", -1);
        h2.put("&", -1);
        h2.put("´", -1);
        h2.put("(", -1);
        h2.put(")", -1);
        h2.put("*", -1);
        h2.put("+", -1);
        h2.put(",", -1);
        h2.put("-", -1);
        h2.put(".", -1);
        h2.put("/", -1);
        h2.put("0", -1);
        h2.put("1", -1);
        h2.put("2", -1);
        h2.put("3", -1);
        h2.put("4", -1);
        h2.put("5", -1);
        h2.put("6", -1);
        h2.put("7", -1);
        h2.put("8", -1);
        h2.put("9", -1);
        h2.put(":", -1);
        h2.put(";", -1);
        h2.put("<", -1);
        h2.put("=", -1);
        h2.put(">", -1);
        h2.put("?", -1);
        h2.put("@", -1);
        h2.put("A", -1);
        h2.put("B", -1);
        h2.put("C", -1);
        h2.put("D", -1);
        h2.put("E", -1);
        h2.put("F", -1);
        h2.put("G", -1);
        h2.put("H", -1);
        h2.put("I", -1);
        h2.put("J", -1);
        h2.put("K", -1);
        h2.put("L", -1);
        h2.put("M", -1);
        h2.put("N", -1);
        h2.put("O", -1);
        h2.put("P", -1);
        h2.put("Q", -1);
        h2.put("R", -1);
        h2.put("S", -1);
        h2.put("T", -1);
        h2.put("U", -1);
        h2.put("V", -1);
        h2.put("X", -1);
        h2.put("W", -1);
        h2.put("Y", -1);
        h2.put("X", -1);
        h2.put("Z", -1);
        h2.put("[", -1);
        h2.put("\'",-1);
        h2.put("]", -1);
        h2.put("^", -1);
        h2.put("_", -1);
        h2.put("`", -1);
        h2.put("a", -1);
        h2.put("b", -1);
        h2.put("c", -1);
        h2.put("d", -1);
        h2.put("e", -1);
        h2.put("f", -1);
        h2.put("g", -1);
        h2.put("h", -1);
        h2.put("i", -1);
        h2.put("j", -1);
        h2.put("k", -1);
        h2.put("l", -1);
        h2.put("m", -1);
        h2.put("n", -1);
        h2.put("o", -1);
        h2.put("p", -1);
        h2.put("q", -1);
        h2.put("r", -1);
        h2.put("s", -1);
        h2.put("t", -1);
        h2.put("u", -1);
        h2.put("v", -1);
        h2.put("w", -1);
        h2.put("x", -1);
        h2.put("y", -1);
        h2.put("z", -1);
        h2.put("{", -1);
        h2.put("|", -1);
        h2.put("}", -1);  
        T.add(h2);
        
        //ESTADO 11 - const
        h2 = new HashMap();
        h2.put("\t",-1);
        h2.put("\n",-1);
        h2.put("\r",-1);
        h2.put(" ", -1);
        h2.put("!", -1);
        h2.put("\"",-1);
        h2.put("#", -1);
        h2.put("$", -1);
        h2.put("%", -1);
        h2.put("&", -1);
        h2.put("´", -1);
        h2.put("(", -1);
        h2.put(")", -1);
        h2.put("*", -1);
        h2.put("+", -1);
        h2.put(",", -1);
        h2.put("-", -1);
        h2.put(".", 24);
        h2.put("/", -1);
        h2.put("0", 25);
        h2.put("1", 25);
        h2.put("2", 25);
        h2.put("3", 25);
        h2.put("4", 25);
        h2.put("5", 25);
        h2.put("6", 25);
        h2.put("7", 25);
        h2.put("8", 25);
        h2.put("9", 25);
        h2.put(":", -1);
        h2.put(";", -1);
        h2.put("<", -1);
        h2.put("=", -1);
        h2.put(">", -1);
        h2.put("?", -1);
        h2.put("@", -1);
        h2.put("A", -1);
        h2.put("B", -1);
        h2.put("C", -1);
        h2.put("D", -1);
        h2.put("E", -1);
        h2.put("F", -1);
        h2.put("G", -1);
        h2.put("H", -1);
        h2.put("I", -1);
        h2.put("J", -1);
        h2.put("K", -1);
        h2.put("L", -1);
        h2.put("M", -1);
        h2.put("N", -1);
        h2.put("O", -1);
        h2.put("P", -1);
        h2.put("Q", -1);
        h2.put("R", -1);
        h2.put("S", -1);
        h2.put("T", -1);
        h2.put("U", -1);
        h2.put("V", -1);
        h2.put("X", -1);
        h2.put("W", -1);
        h2.put("Y", -1);
        h2.put("X", -1);
        h2.put("Z", -1);
        h2.put("[", -1);
        h2.put("\'",-1);
        h2.put("]", -1);
        h2.put("^", -1);
        h2.put("_", -1);
        h2.put("`", -1);
        h2.put("a", -1);
        h2.put("b", -1);
        h2.put("c", -1);
        h2.put("d", -1);
        h2.put("e", -1);
        h2.put("f", -1);
        h2.put("g", -1);
        h2.put("h", -1);
        h2.put("i", -1);
        h2.put("j", -1);
        h2.put("k", -1);
        h2.put("l", -1);
        h2.put("m", -1);
        h2.put("n", -1);
        h2.put("o", -1);
        h2.put("p", -1);
        h2.put("q", -1);
        h2.put("r", -1);
        h2.put("s", -1);
        h2.put("t", -1);
        h2.put("u", -1);
        h2.put("v", -1);
        h2.put("w", -1);
        h2.put("x", -1);
        h2.put("y", -1);
        h2.put("z", -1);
        h2.put("{", -1);
        h2.put("|", -1);
        h2.put("}", -1);  
        T.add(h2);
        
        //ESTADO 12 - dp
        h2 = new HashMap();
        h2.put("\t",-1);
        h2.put("\n",-1);
        h2.put("\r",-1);
        h2.put(" ", -1);
        h2.put("!", -1);
        h2.put("\"",-1);
        h2.put("#", -1);
        h2.put("$", -1);
        h2.put("%", -1);
        h2.put("&", -1);
        h2.put("´", -1);
        h2.put("(", -1);
        h2.put(")", -1);
        h2.put("*", -1);
        h2.put("+", -1);
        h2.put(",", -1);
        h2.put("-", -1);
        h2.put(".", -1);
        h2.put("/", -1);
        h2.put("0", -1);
        h2.put("1", -1);
        h2.put("2", -1);
        h2.put("3", -1);
        h2.put("4", -1);
        h2.put("5", -1);
        h2.put("6", -1);
        h2.put("7", -1);
        h2.put("8", -1);
        h2.put("9", -1);
        h2.put(":", -1);
        h2.put(";", -1);
        h2.put("<", -1);
        h2.put("=", -1);
        h2.put(">", -1);
        h2.put("?", -1);
        h2.put("@", -1);
        h2.put("A", -1);
        h2.put("B", -1);
        h2.put("C", -1);
        h2.put("D", -1);
        h2.put("E", -1);
        h2.put("F", -1);
        h2.put("G", -1);
        h2.put("H", -1);
        h2.put("I", -1);
        h2.put("J", -1);
        h2.put("K", -1);
        h2.put("L", -1);
        h2.put("M", -1);
        h2.put("N", -1);
        h2.put("O", -1);
        h2.put("P", -1);
        h2.put("Q", -1);
        h2.put("R", -1);
        h2.put("S", -1);
        h2.put("T", -1);
        h2.put("U", -1);
        h2.put("V", -1);
        h2.put("X", -1);
        h2.put("W", -1);
        h2.put("Y", -1);
        h2.put("X", -1);
        h2.put("Z", -1);
        h2.put("[", -1);
        h2.put("\'",-1);
        h2.put("]", -1);
        h2.put("^", -1);
        h2.put("_", -1);
        h2.put("`", -1);
        h2.put("a", -1);
        h2.put("b", -1);
        h2.put("c", -1);
        h2.put("d", -1);
        h2.put("e", -1);
        h2.put("f", -1);
        h2.put("g", -1);
        h2.put("h", -1);
        h2.put("i", -1);
        h2.put("j", -1);
        h2.put("k", -1);
        h2.put("l", -1);
        h2.put("m", -1);
        h2.put("n", -1);
        h2.put("o", -1);
        h2.put("p", -1);
        h2.put("q", -1);
        h2.put("r", -1);
        h2.put("s", -1);
        h2.put("t", -1);
        h2.put("u", -1);
        h2.put("v", -1);
        h2.put("w", -1);
        h2.put("x", -1);
        h2.put("y", -1);
        h2.put("z", -1);
        h2.put("{", -1);
        h2.put("|", -1);
        h2.put("}", -1);  
        T.add(h2);
        
        //ESTADO 13 - pv
        h2 = new HashMap();
        h2.put("\t",-1);
        h2.put("\n",-1);
        h2.put("\r",-1);
        h2.put(" ", -1);
        h2.put("!", -1);
        h2.put("\"",-1);
        h2.put("#", -1);
        h2.put("$", -1);
        h2.put("%", -1);
        h2.put("&", -1);
        h2.put("´", -1);
        h2.put("(", -1);
        h2.put(")", -1);
        h2.put("*", -1);
        h2.put("+", -1);
        h2.put(",", -1);
        h2.put("-", -1);
        h2.put(".", -1);
        h2.put("/", -1);
        h2.put("0", -1);
        h2.put("1", -1);
        h2.put("2", -1);
        h2.put("3", -1);
        h2.put("4", -1);
        h2.put("5", -1);
        h2.put("6", -1);
        h2.put("7", -1);
        h2.put("8", -1);
        h2.put("9", -1);
        h2.put(":", -1);
        h2.put(";", -1);
        h2.put("<", -1);
        h2.put("=", -1);
        h2.put(">", -1);
        h2.put("?", -1);
        h2.put("@", -1);
        h2.put("A", -1);
        h2.put("B", -1);
        h2.put("C", -1);
        h2.put("D", -1);
        h2.put("E", -1);
        h2.put("F", -1);
        h2.put("G", -1);
        h2.put("H", -1);
        h2.put("I", -1);
        h2.put("J", -1);
        h2.put("K", -1);
        h2.put("L", -1);
        h2.put("M", -1);
        h2.put("N", -1);
        h2.put("O", -1);
        h2.put("P", -1);
        h2.put("Q", -1);
        h2.put("R", -1);
        h2.put("S", -1);
        h2.put("T", -1);
        h2.put("U", -1);
        h2.put("V", -1);
        h2.put("X", -1);
        h2.put("W", -1);
        h2.put("Y", -1);
        h2.put("X", -1);
        h2.put("Z", -1);
        h2.put("[", -1);
        h2.put("\'",-1);
        h2.put("]", -1);
        h2.put("^", -1);
        h2.put("_", -1);
        h2.put("`", -1);
        h2.put("a", -1);
        h2.put("b", -1);
        h2.put("c", -1);
        h2.put("d", -1);
        h2.put("e", -1);
        h2.put("f", -1);
        h2.put("g", -1);
        h2.put("h", -1);
        h2.put("i", -1);
        h2.put("j", -1);
        h2.put("k", -1);
        h2.put("l", -1);
        h2.put("m", -1);
        h2.put("n", -1);
        h2.put("o", -1);
        h2.put("p", -1);
        h2.put("q", -1);
        h2.put("r", -1);
        h2.put("s", -1);
        h2.put("t", -1);
        h2.put("u", -1);
        h2.put("v", -1);
        h2.put("w", -1);
        h2.put("x", -1);
        h2.put("y", -1);
        h2.put("z", -1);
        h2.put("{", -1);
        h2.put("|", -1);
        h2.put("}", -1);  
        T.add(h2);
        
        //ESTADO 14 - menor
        h2 = new HashMap();
        h2.put("\t",-1);
        h2.put("\n",-1);
        h2.put("\r",-1);
        h2.put(" ", -1);
        h2.put("!", -1);
        h2.put("\"",-1);
        h2.put("#", -1);
        h2.put("$", -1);
        h2.put("%", -1);
        h2.put("&", -1);
        h2.put("´", -1);
        h2.put("(", -1);
        h2.put(")", -1);
        h2.put("*", -1);
        h2.put("+", -1);
        h2.put(",", -1);
        h2.put("-", -1);
        h2.put(".", -1);
        h2.put("/", -1);
        h2.put("0", -1);
        h2.put("1", -1);
        h2.put("2", -1);
        h2.put("3", -1);
        h2.put("4", -1);
        h2.put("5", -1);
        h2.put("6", -1);
        h2.put("7", -1);
        h2.put("8", -1);
        h2.put("9", -1);
        h2.put(":", -1);
        h2.put(";", -1);
        h2.put("<", -1);
        h2.put("=", 26);
        h2.put(">", 27);
        h2.put("?", -1);
        h2.put("@", -1);
        h2.put("A", -1);
        h2.put("B", -1);
        h2.put("C", -1);
        h2.put("D", -1);
        h2.put("E", -1);
        h2.put("F", -1);
        h2.put("G", -1);
        h2.put("H", -1);
        h2.put("I", -1);
        h2.put("J", -1);
        h2.put("K", -1);
        h2.put("L", -1);
        h2.put("M", -1);
        h2.put("N", -1);
        h2.put("O", -1);
        h2.put("P", -1);
        h2.put("Q", -1);
        h2.put("R", -1);
        h2.put("S", -1);
        h2.put("T", -1);
        h2.put("U", -1);
        h2.put("V", -1);
        h2.put("X", -1);
        h2.put("W", -1);
        h2.put("Y", -1);
        h2.put("X", -1);
        h2.put("Z", -1);
        h2.put("[", -1);
        h2.put("\'",-1);
        h2.put("]", -1);
        h2.put("^", -1);
        h2.put("_", -1);
        h2.put("`", -1);
        h2.put("a", -1);
        h2.put("b", -1);
        h2.put("c", -1);
        h2.put("d", -1);
        h2.put("e", -1);
        h2.put("f", -1);
        h2.put("g", -1);
        h2.put("h", -1);
        h2.put("i", -1);
        h2.put("j", -1);
        h2.put("k", -1);
        h2.put("l", -1);
        h2.put("m", -1);
        h2.put("n", -1);
        h2.put("o", -1);
        h2.put("p", -1);
        h2.put("q", -1);
        h2.put("r", -1);
        h2.put("s", -1);
        h2.put("t", -1);
        h2.put("u", -1);
        h2.put("v", -1);
        h2.put("w", -1);
        h2.put("x", -1);
        h2.put("y", -1);
        h2.put("z", -1);
        h2.put("{", -1);
        h2.put("|", -1);
        h2.put("}", -1);  
        T.add(h2);
        
        //ESTADO 15 - at
        h2 = new HashMap();
        h2.put("\t",-1);
        h2.put("\n",-1);
        h2.put("\r",-1);
        h2.put(" ", -1);
        h2.put("!", -1);
        h2.put("\"",-1);
        h2.put("#", -1);
        h2.put("$", -1);
        h2.put("%", -1);
        h2.put("&", -1);
        h2.put("´", -1);
        h2.put("(", -1);
        h2.put(")", -1);
        h2.put("*", -1);
        h2.put("+", -1);
        h2.put(",", -1);
        h2.put("-", -1);
        h2.put(".", -1);
        h2.put("/", -1);
        h2.put("0", -1);
        h2.put("1", -1);
        h2.put("2", -1);
        h2.put("3", -1);
        h2.put("4", -1);
        h2.put("5", -1);
        h2.put("6", -1);
        h2.put("7", -1);
        h2.put("8", -1);
        h2.put("9", -1);
        h2.put(":", -1);
        h2.put(";", -1);
        h2.put("<", -1);
        h2.put("=", 28);
        h2.put(">", -1);
        h2.put("?", -1);
        h2.put("@", -1);
        h2.put("A", -1);
        h2.put("B", -1);
        h2.put("C", -1);
        h2.put("D", -1);
        h2.put("E", -1);
        h2.put("F", -1);
        h2.put("G", -1);
        h2.put("H", -1);
        h2.put("I", -1);
        h2.put("J", -1);
        h2.put("K", -1);
        h2.put("L", -1);
        h2.put("M", -1);
        h2.put("N", -1);
        h2.put("O", -1);
        h2.put("P", -1);
        h2.put("Q", -1);
        h2.put("R", -1);
        h2.put("S", -1);
        h2.put("T", -1);
        h2.put("U", -1);
        h2.put("V", -1);
        h2.put("X", -1);
        h2.put("W", -1);
        h2.put("Y", -1);
        h2.put("X", -1);
        h2.put("Z", -1);
        h2.put("[", -1);
        h2.put("\'",-1);
        h2.put("]", -1);
        h2.put("^", -1);
        h2.put("_", -1);
        h2.put("`", -1);
        h2.put("a", -1);
        h2.put("b", -1);
        h2.put("c", -1);
        h2.put("d", -1);
        h2.put("e", -1);
        h2.put("f", -1);
        h2.put("g", -1);
        h2.put("h", -1);
        h2.put("i", -1);
        h2.put("j", -1);
        h2.put("k", -1);
        h2.put("l", -1);
        h2.put("m", -1);
        h2.put("n", -1);
        h2.put("o", -1);
        h2.put("p", -1);
        h2.put("q", -1);
        h2.put("r", -1);
        h2.put("s", -1);
        h2.put("t", -1);
        h2.put("u", -1);
        h2.put("v", -1);
        h2.put("w", -1);
        h2.put("x", -1);
        h2.put("y", -1);
        h2.put("z", -1);
        h2.put("{", -1);
        h2.put("|", -1);
        h2.put("}", -1);  
        T.add(h2);
        
        //ESTADO 16 - maior
        h2 = new HashMap();
        h2.put("\t",-1);
        h2.put("\n",-1);
        h2.put("\r",-1);
        h2.put(" ", -1);
        h2.put("!", -1);
        h2.put("\"",-1);
        h2.put("#", -1);
        h2.put("$", -1);
        h2.put("%", -1);
        h2.put("&", -1);
        h2.put("´", -1);
        h2.put("(", -1);
        h2.put(")", -1);
        h2.put("*", -1);
        h2.put("+", -1);
        h2.put(",", -1);
        h2.put("-", -1);
        h2.put(".", -1);
        h2.put("/", -1);
        h2.put("0", -1);
        h2.put("1", -1);
        h2.put("2", -1);
        h2.put("3", -1);
        h2.put("4", -1);
        h2.put("5", -1);
        h2.put("6", -1);
        h2.put("7", -1);
        h2.put("8", -1);
        h2.put("9", -1);
        h2.put(":", -1);
        h2.put(";", -1);
        h2.put("<", -1);
        h2.put("=", 29);
        h2.put(">", -1);
        h2.put("?", -1);
        h2.put("@", -1);
        h2.put("A", -1);
        h2.put("B", -1);
        h2.put("C", -1);
        h2.put("D", -1);
        h2.put("E", -1);
        h2.put("F", -1);
        h2.put("G", -1);
        h2.put("H", -1);
        h2.put("I", -1);
        h2.put("J", -1);
        h2.put("K", -1);
        h2.put("L", -1);
        h2.put("M", -1);
        h2.put("N", -1);
        h2.put("O", -1);
        h2.put("P", -1);
        h2.put("Q", -1);
        h2.put("R", -1);
        h2.put("S", -1);
        h2.put("T", -1);
        h2.put("U", -1);
        h2.put("V", -1);
        h2.put("X", -1);
        h2.put("W", -1);
        h2.put("Y", -1);
        h2.put("X", -1);
        h2.put("Z", -1);
        h2.put("[", -1);
        h2.put("\'",-1);
        h2.put("]", -1);
        h2.put("^", -1);
        h2.put("_", -1);
        h2.put("`", -1);
        h2.put("a", -1);
        h2.put("b", -1);
        h2.put("c", -1);
        h2.put("d", -1);
        h2.put("e", -1);
        h2.put("f", -1);
        h2.put("g", -1);
        h2.put("h", -1);
        h2.put("i", -1);
        h2.put("j", -1);
        h2.put("k", -1);
        h2.put("l", -1);
        h2.put("m", -1);
        h2.put("n", -1);
        h2.put("o", -1);
        h2.put("p", -1);
        h2.put("q", -1);
        h2.put("r", -1);
        h2.put("s", -1);
        h2.put("t", -1);
        h2.put("u", -1);
        h2.put("v", -1);
        h2.put("w", -1);
        h2.put("x", -1);
        h2.put("y", -1);
        h2.put("z", -1);
        h2.put("{", -1);
        h2.put("|", -1);
        h2.put("}", -1);  
        T.add(h2);
        
        //ESTADO 17 - id
        h2 = new HashMap();
        h2.put("\t",-1);
        h2.put("\n",-1);
        h2.put("\r",-1);
        h2.put(" ", -1);
        h2.put("!", -1);
        h2.put("\"",-1);
        h2.put("#", -1);
        h2.put("$", -1);
        h2.put("%", -1);
        h2.put("&", -1);
        h2.put("´", -1);
        h2.put("(", -1);
        h2.put(")", -1);
        h2.put("*", -1);
        h2.put("+", -1);
        h2.put(",", -1);
        h2.put("-", -1);
        h2.put(".", -1);
        h2.put("/", -1);
        h2.put("0", 17);
        h2.put("1", 17);
        h2.put("2", 17);
        h2.put("3", 17);
        h2.put("4", 17);
        h2.put("5", 17);
        h2.put("6", 17);
        h2.put("7", 17);
        h2.put("8", 17);
        h2.put("9", 17);
        h2.put(":", -1);
        h2.put(";", -1);
        h2.put("<", -1);
        h2.put("=", -1);
        h2.put(">", -1);
        h2.put("?", -1);
        h2.put("@", -1);
        h2.put("A", 17);
        h2.put("B", 17);
        h2.put("C", 17);
        h2.put("D", 17);
        h2.put("E", 17);
        h2.put("F", 17);
        h2.put("G", 17);
        h2.put("H", 17);
        h2.put("I", 17);
        h2.put("J", 17);
        h2.put("K", 17);
        h2.put("L", 17);
        h2.put("M", 17);
        h2.put("N", 17);
        h2.put("O", 17);
        h2.put("P", 17);
        h2.put("Q", 17);
        h2.put("R", 17);
        h2.put("S", 17);
        h2.put("T", 17);
        h2.put("U", 17);
        h2.put("V", 17);
        h2.put("X", 17);
        h2.put("W", 17);
        h2.put("Y", 17);
        h2.put("X", 17);
        h2.put("Z", 17);
        h2.put("[", -1);
        h2.put("\'",-1);
        h2.put("]", -1);
        h2.put("^", -1);
        h2.put("_", 17);
        h2.put("`", -1);
        h2.put("a", 17);
        h2.put("b", 17);
        h2.put("c", 17);
        h2.put("d", 17);
        h2.put("e", 17);
        h2.put("f", 17);
        h2.put("g", 17);
        h2.put("h", 17);
        h2.put("i", 17);
        h2.put("j", 17);
        h2.put("k", 17);
        h2.put("l", 17);
        h2.put("m", 17);
        h2.put("n", 17);
        h2.put("o", 17);
        h2.put("p", 17);
        h2.put("q", 17);
        h2.put("r", 17);
        h2.put("s", 17);
        h2.put("t", 17);
        h2.put("u", 17);
        h2.put("v", 17);
        h2.put("w", 17);
        h2.put("x", 17);
        h2.put("y", 17);
        h2.put("z", 17);
        h2.put("{", -1);
        h2.put("|", -1);
        h2.put("}", -1);  
        T.add(h2);
        
        //ESTADO 18 - ac
        h2 = new HashMap();
        h2.put("\t",-1);
        h2.put("\n",-1);
        h2.put("\r",-1);
        h2.put(" ", -1);
        h2.put("!", -1);
        h2.put("\"",-1);
        h2.put("#", -1);
        h2.put("$", -1);
        h2.put("%", -1);
        h2.put("&", -1);
        h2.put("´", -1);
        h2.put("(", -1);
        h2.put(")", -1);
        h2.put("*", -1);
        h2.put("+", -1);
        h2.put(",", -1);
        h2.put("-", -1);
        h2.put(".", -1);
        h2.put("/", -1);
        h2.put("0", -1);
        h2.put("1", -1);
        h2.put("2", -1);
        h2.put("3", -1);
        h2.put("4", -1);
        h2.put("5", -1);
        h2.put("6", -1);
        h2.put("7", -1);
        h2.put("8", -1);
        h2.put("9", -1);
        h2.put(":", -1);
        h2.put(";", -1);
        h2.put("<", -1);
        h2.put("=", -1);
        h2.put(">", -1);
        h2.put("?", -1);
        h2.put("@", -1);
        h2.put("A", -1);
        h2.put("B", -1);
        h2.put("C", -1);
        h2.put("D", -1);
        h2.put("E", -1);
        h2.put("F", -1);
        h2.put("G", -1);
        h2.put("H", -1);
        h2.put("I", -1);
        h2.put("J", -1);
        h2.put("K", -1);
        h2.put("L", -1);
        h2.put("M", -1);
        h2.put("N", -1);
        h2.put("O", -1);
        h2.put("P", -1);
        h2.put("Q", -1);
        h2.put("R", -1);
        h2.put("S", -1);
        h2.put("T", -1);
        h2.put("U", -1);
        h2.put("V", -1);
        h2.put("X", -1);
        h2.put("W", -1);
        h2.put("Y", -1);
        h2.put("X", -1);
        h2.put("Z", -1);
        h2.put("[", -1);
        h2.put("\'",-1);
        h2.put("]", -1);
        h2.put("^", -1);
        h2.put("_", -1);
        h2.put("`", -1);
        h2.put("a", -1);
        h2.put("b", -1);
        h2.put("c", -1);
        h2.put("d", -1);
        h2.put("e", -1);
        h2.put("f", -1);
        h2.put("g", -1);
        h2.put("h", -1);
        h2.put("i", -1);
        h2.put("j", -1);
        h2.put("k", -1);
        h2.put("l", -1);
        h2.put("m", -1);
        h2.put("n", -1);
        h2.put("o", -1);
        h2.put("p", -1);
        h2.put("q", -1);
        h2.put("r", -1);
        h2.put("s", -1);
        h2.put("t", -1);
        h2.put("u", -1);
        h2.put("v", -1);
        h2.put("w", -1);
        h2.put("x", -1);
        h2.put("y", -1);
        h2.put("z", -1);
        h2.put("{", -1);
        h2.put("|", -1);
        h2.put("}", -1);  
        T.add(h2);
        
        //ESTADO 19 - ?
        h2 = new HashMap();
        h2.put("\t",-1);
        h2.put("\n",-1);
        h2.put("\r",-1);
        h2.put(" ", -1);
        h2.put("!", -1);
        h2.put("\"",-1);
        h2.put("#", -1);
        h2.put("$", -1);
        h2.put("%", -1);
        h2.put("&", -1);
        h2.put("´", -1);
        h2.put("(", -1);
        h2.put(")", -1);
        h2.put("*", -1);
        h2.put("+", -1);
        h2.put(",", -1);
        h2.put("-", -1);
        h2.put(".", -1);
        h2.put("/", -1);
        h2.put("0", -1);
        h2.put("1", -1);
        h2.put("2", -1);
        h2.put("3", -1);
        h2.put("4", -1);
        h2.put("5", -1);
        h2.put("6", -1);
        h2.put("7", -1);
        h2.put("8", -1);
        h2.put("9", -1);
        h2.put(":", -1);
        h2.put(";", -1);
        h2.put("<", -1);
        h2.put("=", -1);
        h2.put(">", -1);
        h2.put("?", -1);
        h2.put("@", -1);
        h2.put("A", -1);
        h2.put("B", -1);
        h2.put("C", -1);
        h2.put("D", -1);
        h2.put("E", -1);
        h2.put("F", -1);
        h2.put("G", -1);
        h2.put("H", -1);
        h2.put("I", -1);
        h2.put("J", -1);
        h2.put("K", -1);
        h2.put("L", -1);
        h2.put("M", -1);
        h2.put("N", -1);
        h2.put("O", -1);
        h2.put("P", -1);
        h2.put("Q", -1);
        h2.put("R", -1);
        h2.put("S", -1);
        h2.put("T", -1);
        h2.put("U", -1);
        h2.put("V", -1);
        h2.put("X", -1);
        h2.put("W", -1);
        h2.put("Y", -1);
        h2.put("X", -1);
        h2.put("Z", -1);
        h2.put("[", -1);
        h2.put("\'",-1);
        h2.put("]", -1);
        h2.put("^", -1);
        h2.put("_", -1);
        h2.put("`", -1);
        h2.put("a", -1);
        h2.put("b", -1);
        h2.put("c", -1);
        h2.put("d", -1);
        h2.put("e", -1);
        h2.put("f", -1);
        h2.put("g", -1);
        h2.put("h", -1);
        h2.put("i", -1);
        h2.put("j", -1);
        h2.put("k", -1);
        h2.put("l", -1);
        h2.put("m", -1);
        h2.put("n", -1);
        h2.put("o", -1);
        h2.put("p", -1);
        h2.put("q", -1);
        h2.put("r", -1);
        h2.put("s", -1);
        h2.put("t", -1);
        h2.put("u", -1);
        h2.put("v", -1);
        h2.put("w", -1);
        h2.put("x", -1);
        h2.put("y", -1);
        h2.put("z", -1);
        h2.put("{", -1);
        h2.put("|", 30);
        h2.put("}", -1);  
        T.add(h2);
        
        //ESTADO 20 - fc
        h2 = new HashMap();
        h2.put("\t",-1);
        h2.put("\n",-1);
        h2.put("\r",-1);
        h2.put(" ", -1);
        h2.put("!", -1);
        h2.put("\"",-1);
        h2.put("#", -1);
        h2.put("$", -1);
        h2.put("%", -1);
        h2.put("&", -1);
        h2.put("´", -1);
        h2.put("(", -1);
        h2.put(")", -1);
        h2.put("*", -1);
        h2.put("+", -1);
        h2.put(",", -1);
        h2.put("-", -1);
        h2.put(".", -1);
        h2.put("/", -1);
        h2.put("0", -1);
        h2.put("1", -1);
        h2.put("2", -1);
        h2.put("3", -1);
        h2.put("4", -1);
        h2.put("5", -1);
        h2.put("6", -1);
        h2.put("7", -1);
        h2.put("8", -1);
        h2.put("9", -1);
        h2.put(":", -1);
        h2.put(";", -1);
        h2.put("<", -1);
        h2.put("=", -1);
        h2.put(">", -1);
        h2.put("?", -1);
        h2.put("@", -1);
        h2.put("A", -1);
        h2.put("B", -1);
        h2.put("C", -1);
        h2.put("D", -1);
        h2.put("E", -1);
        h2.put("F", -1);
        h2.put("G", -1);
        h2.put("H", -1);
        h2.put("I", -1);
        h2.put("J", -1);
        h2.put("K", -1);
        h2.put("L", -1);
        h2.put("M", -1);
        h2.put("N", -1);
        h2.put("O", -1);
        h2.put("P", -1);
        h2.put("Q", -1);
        h2.put("R", -1);
        h2.put("S", -1);
        h2.put("T", -1);
        h2.put("U", -1);
        h2.put("V", -1);
        h2.put("X", -1);
        h2.put("W", -1);
        h2.put("Y", -1);
        h2.put("X", -1);
        h2.put("Z", -1);
        h2.put("[", -1);
        h2.put("\'",-1);
        h2.put("]", -1);
        h2.put("^", -1);
        h2.put("_", -1);
        h2.put("`", -1);
        h2.put("a", -1);
        h2.put("b", -1);
        h2.put("c", -1);
        h2.put("d", -1);
        h2.put("e", -1);
        h2.put("f", -1);
        h2.put("g", -1);
        h2.put("h", -1);
        h2.put("i", -1);
        h2.put("j", -1);
        h2.put("k", -1);
        h2.put("l", -1);
        h2.put("m", -1);
        h2.put("n", -1);
        h2.put("o", -1);
        h2.put("p", -1);
        h2.put("q", -1);
        h2.put("r", -1);
        h2.put("s", -1);
        h2.put("t", -1);
        h2.put("u", -1);
        h2.put("v", -1);
        h2.put("w", -1);
        h2.put("x", -1);
        h2.put("y", -1);
        h2.put("z", -1);
        h2.put("{", -1);
        h2.put("|", -1);
        h2.put("}", -1);  
        T.add(h2);
        
        //ESTADO 21 - e
        h2 = new HashMap();
        h2.put("\t",-1);
        h2.put("\n",-1);
        h2.put("\r",-1);
        h2.put(" ", -1);
        h2.put("!", -1);
        h2.put("\"",-1);
        h2.put("#", -1);
        h2.put("$", -1);
        h2.put("%", -1);
        h2.put("&", -1);
        h2.put("´", -1);
        h2.put("(", -1);
        h2.put(")", -1);
        h2.put("*", -1);
        h2.put("+", -1);
        h2.put(",", -1);
        h2.put("-", -1);
        h2.put(".", -1);
        h2.put("/", -1);
        h2.put("0", -1);
        h2.put("1", -1);
        h2.put("2", -1);
        h2.put("3", -1);
        h2.put("4", -1);
        h2.put("5", -1);
        h2.put("6", -1);
        h2.put("7", -1);
        h2.put("8", -1);
        h2.put("9", -1);
        h2.put(":", -1);
        h2.put(";", -1);
        h2.put("<", -1);
        h2.put("=", -1);
        h2.put(">", -1);
        h2.put("?", -1);
        h2.put("@", -1);
        h2.put("A", -1);
        h2.put("B", -1);
        h2.put("C", -1);
        h2.put("D", -1);
        h2.put("E", -1);
        h2.put("F", -1);
        h2.put("G", -1);
        h2.put("H", -1);
        h2.put("I", -1);
        h2.put("J", -1);
        h2.put("K", -1);
        h2.put("L", -1);
        h2.put("M", -1);
        h2.put("N", -1);
        h2.put("O", -1);
        h2.put("P", -1);
        h2.put("Q", -1);
        h2.put("R", -1);
        h2.put("S", -1);
        h2.put("T", -1);
        h2.put("U", -1);
        h2.put("V", -1);
        h2.put("X", -1);
        h2.put("W", -1);
        h2.put("Y", -1);
        h2.put("X", -1);
        h2.put("Z", -1);
        h2.put("[", -1);
        h2.put("\'",-1);
        h2.put("]", -1);
        h2.put("^", -1);
        h2.put("_", -1);
        h2.put("`", -1);
        h2.put("a", -1);
        h2.put("b", -1);
        h2.put("c", -1);
        h2.put("d", -1);
        h2.put("e", -1);
        h2.put("f", -1);
        h2.put("g", -1);
        h2.put("h", -1);
        h2.put("i", -1);
        h2.put("j", -1);
        h2.put("k", -1);
        h2.put("l", -1);
        h2.put("m", -1);
        h2.put("n", -1);
        h2.put("o", -1);
        h2.put("p", -1);
        h2.put("q", -1);
        h2.put("r", -1);
        h2.put("s", -1);
        h2.put("t", -1);
        h2.put("u", -1);
        h2.put("v", -1);
        h2.put("w", -1);
        h2.put("x", -1);
        h2.put("y", -1);
        h2.put("z", -1);
        h2.put("{", -1);
        h2.put("|", -1);
        h2.put("}", -1);  
        T.add(h2);
        
        //ESTADO 22 - inc
        h2 = new HashMap();
        h2.put("\t",-1);
        h2.put("\n",-1);
        h2.put("\r",-1);
        h2.put(" ", -1);
        h2.put("!", -1);
        h2.put("\"",-1);
        h2.put("#", -1);
        h2.put("$", -1);
        h2.put("%", -1);
        h2.put("&", -1);
        h2.put("´", -1);
        h2.put("(", -1);
        h2.put(")", -1);
        h2.put("*", -1);
        h2.put("+", -1);
        h2.put(",", -1);
        h2.put("-", -1);
        h2.put(".", -1);
        h2.put("/", -1);
        h2.put("0", -1);
        h2.put("1", -1);
        h2.put("2", -1);
        h2.put("3", -1);
        h2.put("4", -1);
        h2.put("5", -1);
        h2.put("6", -1);
        h2.put("7", -1);
        h2.put("8", -1);
        h2.put("9", -1);
        h2.put(":", -1);
        h2.put(";", -1);
        h2.put("<", -1);
        h2.put("=", -1);
        h2.put(">", -1);
        h2.put("?", -1);
        h2.put("@", -1);
        h2.put("A", -1);
        h2.put("B", -1);
        h2.put("C", -1);
        h2.put("D", -1);
        h2.put("E", -1);
        h2.put("F", -1);
        h2.put("G", -1);
        h2.put("H", -1);
        h2.put("I", -1);
        h2.put("J", -1);
        h2.put("K", -1);
        h2.put("L", -1);
        h2.put("M", -1);
        h2.put("N", -1);
        h2.put("O", -1);
        h2.put("P", -1);
        h2.put("Q", -1);
        h2.put("R", -1);
        h2.put("S", -1);
        h2.put("T", -1);
        h2.put("U", -1);
        h2.put("V", -1);
        h2.put("X", -1);
        h2.put("W", -1);
        h2.put("Y", -1);
        h2.put("X", -1);
        h2.put("Z", -1);
        h2.put("[", -1);
        h2.put("\'",-1);
        h2.put("]", -1);
        h2.put("^", -1);
        h2.put("_", -1);
        h2.put("`", -1);
        h2.put("a", -1);
        h2.put("b", -1);
        h2.put("c", -1);
        h2.put("d", -1);
        h2.put("e", -1);
        h2.put("f", -1);
        h2.put("g", -1);
        h2.put("h", -1);
        h2.put("i", -1);
        h2.put("j", -1);
        h2.put("k", -1);
        h2.put("l", -1);
        h2.put("m", -1);
        h2.put("n", -1);
        h2.put("o", -1);
        h2.put("p", -1);
        h2.put("q", -1);
        h2.put("r", -1);
        h2.put("s", -1);
        h2.put("t", -1);
        h2.put("u", -1);
        h2.put("v", -1);
        h2.put("w", -1);
        h2.put("x", -1);
        h2.put("y", -1);
        h2.put("z", -1);
        h2.put("{", -1);
        h2.put("|", -1);
        h2.put("}", -1);  
        T.add(h2);
        
        //ESTADO 23 - DEC
        h2 = new HashMap();
        h2.put("\t",-1);
        h2.put("\n",-1);
        h2.put("\r",-1);
        h2.put(" ", -1);
        h2.put("!", -1);
        h2.put("\"",-1);
        h2.put("#", -1);
        h2.put("$", -1);
        h2.put("%", -1);
        h2.put("&", -1);
        h2.put("´", -1);
        h2.put("(", -1);
        h2.put(")", -1);
        h2.put("*", -1);
        h2.put("+", -1);
        h2.put(",", -1);
        h2.put("-", -1);
        h2.put(".", -1);
        h2.put("/", -1);
        h2.put("0", -1);
        h2.put("1", -1);
        h2.put("2", -1);
        h2.put("3", -1);
        h2.put("4", -1);
        h2.put("5", -1);
        h2.put("6", -1);
        h2.put("7", -1);
        h2.put("8", -1);
        h2.put("9", -1);
        h2.put(":", -1);
        h2.put(";", -1);
        h2.put("<", -1);
        h2.put("=", -1);
        h2.put(">", -1);
        h2.put("?", -1);
        h2.put("@", -1);
        h2.put("A", -1);
        h2.put("B", -1);
        h2.put("C", -1);
        h2.put("D", -1);
        h2.put("E", -1);
        h2.put("F", -1);
        h2.put("G", -1);
        h2.put("H", -1);
        h2.put("I", -1);
        h2.put("J", -1);
        h2.put("K", -1);
        h2.put("L", -1);
        h2.put("M", -1);
        h2.put("N", -1);
        h2.put("O", -1);
        h2.put("P", -1);
        h2.put("Q", -1);
        h2.put("R", -1);
        h2.put("S", -1);
        h2.put("T", -1);
        h2.put("U", -1);
        h2.put("V", -1);
        h2.put("X", -1);
        h2.put("W", -1);
        h2.put("Y", -1);
        h2.put("X", -1);
        h2.put("Z", -1);
        h2.put("[", -1);
        h2.put("\'",-1);
        h2.put("]", -1);
        h2.put("^", -1);
        h2.put("_", -1);
        h2.put("`", -1);
        h2.put("a", -1);
        h2.put("b", -1);
        h2.put("c", -1);
        h2.put("d", -1);
        h2.put("e", -1);
        h2.put("f", -1);
        h2.put("g", -1);
        h2.put("h", -1);
        h2.put("i", -1);
        h2.put("j", -1);
        h2.put("k", -1);
        h2.put("l", -1);
        h2.put("m", -1);
        h2.put("n", -1);
        h2.put("o", -1);
        h2.put("p", -1);
        h2.put("q", -1);
        h2.put("r", -1);
        h2.put("s", -1);
        h2.put("t", -1);
        h2.put("u", -1);
        h2.put("v", -1);
        h2.put("w", -1);
        h2.put("x", -1);
        h2.put("y", -1);
        h2.put("z", -1);
        h2.put("{", -1);
        h2.put("|", -1);
        h2.put("}", -1);  
        T.add(h2);
        
        //ESTADO 24 - ? 
        h2 = new HashMap();
        h2.put("\t",-1);
        h2.put("\n",-1);
        h2.put("\r",-1);
        h2.put(" ", -1);
        h2.put("!", -1);
        h2.put("\"",-1);
        h2.put("#", -1);
        h2.put("$", -1);
        h2.put("%", -1);
        h2.put("&", -1);
        h2.put("´", -1);
        h2.put("(", -1);
        h2.put(")", -1);
        h2.put("*", -1);
        h2.put("+", -1);
        h2.put(",", -1);
        h2.put("-", -1);
        h2.put(".", 24);
        h2.put("/", -1);
        h2.put("0", 31);
        h2.put("1", 31);
        h2.put("2", 31);
        h2.put("3", 31);
        h2.put("4", 31);
        h2.put("5", 31);
        h2.put("6", 31);
        h2.put("7", 31);
        h2.put("8", 31);
        h2.put("9", 31);
        h2.put(":", -1);
        h2.put(";", -1);
        h2.put("<", -1);
        h2.put("=", -1);
        h2.put(">", -1);
        h2.put("?", -1);
        h2.put("@", -1);
        h2.put("A", -1);
        h2.put("B", -1);
        h2.put("C", -1);
        h2.put("D", -1);
        h2.put("E", -1);
        h2.put("F", -1);
        h2.put("G", -1);
        h2.put("H", -1);
        h2.put("I", -1);
        h2.put("J", -1);
        h2.put("K", -1);
        h2.put("L", -1);
        h2.put("M", -1);
        h2.put("N", -1);
        h2.put("O", -1);
        h2.put("P", -1);
        h2.put("Q", -1);
        h2.put("R", -1);
        h2.put("S", -1);
        h2.put("T", -1);
        h2.put("U", -1);
        h2.put("V", -1);
        h2.put("X", -1);
        h2.put("W", -1);
        h2.put("Y", -1);
        h2.put("X", -1);
        h2.put("Z", -1);
        h2.put("[", -1);
        h2.put("\'",-1);
        h2.put("]", -1);
        h2.put("^", -1);
        h2.put("_", -1);
        h2.put("`", -1);
        h2.put("a", -1);
        h2.put("b", -1);
        h2.put("c", -1);
        h2.put("d", -1);
        h2.put("e", -1);
        h2.put("f", -1);
        h2.put("g", -1);
        h2.put("h", -1);
        h2.put("i", -1);
        h2.put("j", -1);
        h2.put("k", -1);
        h2.put("l", -1);
        h2.put("m", -1);
        h2.put("n", -1);
        h2.put("o", -1);
        h2.put("p", -1);
        h2.put("q", -1);
        h2.put("r", -1);
        h2.put("s", -1);
        h2.put("t", -1);
        h2.put("u", -1);
        h2.put("v", -1);
        h2.put("w", -1);
        h2.put("x", -1);
        h2.put("y", -1);
        h2.put("z", -1);
        h2.put("{", -1);
        h2.put("|", -1);
        h2.put("}", -1);  
        T.add(h2);
        
        //ESTADO 25 - const
        h2 = new HashMap();
        h2.put("\t",-1);
        h2.put("\n",-1);
        h2.put("\r",-1);
        h2.put(" ", -1);
        h2.put("!", -1);
        h2.put("\"",-1);
        h2.put("#", -1);
        h2.put("$", -1);
        h2.put("%", -1);
        h2.put("&", -1);
        h2.put("´", -1);
        h2.put("(", -1);
        h2.put(")", -1);
        h2.put("*", -1);
        h2.put("+", -1);
        h2.put(",", -1);
        h2.put("-", -1);
        h2.put(".", -1);
        h2.put("/", -1);
        h2.put("0", 32);
        h2.put("1", 32);
        h2.put("2", 32);
        h2.put("3", 32);
        h2.put("4", 32);
        h2.put("5", 32);
        h2.put("6", 32);
        h2.put("7", 32);
        h2.put("8", 32);
        h2.put("9", 32);
        h2.put(":", -1);
        h2.put(";", -1);
        h2.put("<", -1);
        h2.put("=", -1);
        h2.put(">", -1);
        h2.put("?", -1);
        h2.put("@", -1);
        h2.put("A", -1);
        h2.put("B", -1);
        h2.put("C", -1);
        h2.put("D", -1);
        h2.put("E", -1);
        h2.put("F", -1);
        h2.put("G", -1);
        h2.put("H", -1);
        h2.put("I", -1);
        h2.put("J", -1);
        h2.put("K", -1);
        h2.put("L", -1);
        h2.put("M", -1);
        h2.put("N", -1);
        h2.put("O", -1);
        h2.put("P", -1);
        h2.put("Q", -1);
        h2.put("R", -1);
        h2.put("S", -1);
        h2.put("T", -1);
        h2.put("U", -1);
        h2.put("V", -1);
        h2.put("X", -1);
        h2.put("W", -1);
        h2.put("Y", -1);
        h2.put("X", -1);
        h2.put("Z", -1);
        h2.put("[", -1);
        h2.put("\'",-1);
        h2.put("]", -1);
        h2.put("^", -1);
        h2.put("_", -1);
        h2.put("`", -1);
        h2.put("a", -1);
        h2.put("b", -1);
        h2.put("c", -1);
        h2.put("d", -1);
        h2.put("e", -1);
        h2.put("f", -1);
        h2.put("g", -1);
        h2.put("h", -1);
        h2.put("i", -1);
        h2.put("j", -1);
        h2.put("k", -1);
        h2.put("l", -1);
        h2.put("m", -1);
        h2.put("n", -1);
        h2.put("o", -1);
        h2.put("p", -1);
        h2.put("q", -1);
        h2.put("r", -1);
        h2.put("s", -1);
        h2.put("t", -1);
        h2.put("u", -1);
        h2.put("v", -1);
        h2.put("w", -1);
        h2.put("x", -1);
        h2.put("y", -1);
        h2.put("z", -1);
        h2.put("{", -1);
        h2.put("|", -1);
        h2.put("}", -1);  
        T.add(h2);
        
        //ESTADO 26 - menorig
        h2 = new HashMap();
        h2.put("\t",-1);
        h2.put("\n",-1);
        h2.put("\r",-1);
        h2.put(" ", -1);
        h2.put("!", -1);
        h2.put("\"",-1);
        h2.put("#", -1);
        h2.put("$", -1);
        h2.put("%", -1);
        h2.put("&", -1);
        h2.put("´", -1);
        h2.put("(", -1);
        h2.put(")", -1);
        h2.put("*", -1);
        h2.put("+", -1);
        h2.put(",", -1);
        h2.put("-", -1);
        h2.put(".", -1);
        h2.put("/", -1);
        h2.put("0", -1);
        h2.put("1", -1);
        h2.put("2", -1);
        h2.put("3", -1);
        h2.put("4", -1);
        h2.put("5", -1);
        h2.put("6", -1);
        h2.put("7", -1);
        h2.put("8", -1);
        h2.put("9", -1);
        h2.put(":", -1);
        h2.put(";", -1);
        h2.put("<", -1);
        h2.put("=", -1);
        h2.put(">", -1);
        h2.put("?", -1);
        h2.put("@", -1);
        h2.put("A", -1);
        h2.put("B", -1);
        h2.put("C", -1);
        h2.put("D", -1);
        h2.put("E", -1);
        h2.put("F", -1);
        h2.put("G", -1);
        h2.put("H", -1);
        h2.put("I", -1);
        h2.put("J", -1);
        h2.put("K", -1);
        h2.put("L", -1);
        h2.put("M", -1);
        h2.put("N", -1);
        h2.put("O", -1);
        h2.put("P", -1);
        h2.put("Q", -1);
        h2.put("R", -1);
        h2.put("S", -1);
        h2.put("T", -1);
        h2.put("U", -1);
        h2.put("V", -1);
        h2.put("X", -1);
        h2.put("W", -1);
        h2.put("Y", -1);
        h2.put("X", -1);
        h2.put("Z", -1);
        h2.put("[", -1);
        h2.put("\'",-1);
        h2.put("]", -1);
        h2.put("^", -1);
        h2.put("_", -1);
        h2.put("`", -1);
        h2.put("a", -1);
        h2.put("b", -1);
        h2.put("c", -1);
        h2.put("d", -1);
        h2.put("e", -1);
        h2.put("f", -1);
        h2.put("g", -1);
        h2.put("h", -1);
        h2.put("i", -1);
        h2.put("j", -1);
        h2.put("k", -1);
        h2.put("l", -1);
        h2.put("m", -1);
        h2.put("n", -1);
        h2.put("o", -1);
        h2.put("p", -1);
        h2.put("q", -1);
        h2.put("r", -1);
        h2.put("s", -1);
        h2.put("t", -1);
        h2.put("u", -1);
        h2.put("v", -1);
        h2.put("w", -1);
        h2.put("x", -1);
        h2.put("y", -1);
        h2.put("z", -1);
        h2.put("{", -1);
        h2.put("|", -1);
        h2.put("}", -1);  
        T.add(h2);
        
        //ESTADO 27 - dif
        h2 = new HashMap();
        h2.put("\t",-1);
        h2.put("\n",-1);
        h2.put("\r",-1);
        h2.put(" ", -1);
        h2.put("!", -1);
        h2.put("\"",-1);
        h2.put("#", -1);
        h2.put("$", -1);
        h2.put("%", -1);
        h2.put("&", -1);
        h2.put("´", -1);
        h2.put("(", -1);
        h2.put(")", -1);
        h2.put("*", -1);
        h2.put("+", -1);
        h2.put(",", -1);
        h2.put("-", -1);
        h2.put(".", -1);
        h2.put("/", -1);
        h2.put("0", -1);
        h2.put("1", -1);
        h2.put("2", -1);
        h2.put("3", -1);
        h2.put("4", -1);
        h2.put("5", -1);
        h2.put("6", -1);
        h2.put("7", -1);
        h2.put("8", -1);
        h2.put("9", -1);
        h2.put(":", -1);
        h2.put(";", -1);
        h2.put("<", -1);
        h2.put("=", -1);
        h2.put(">", -1);
        h2.put("?", -1);
        h2.put("@", -1);
        h2.put("A", -1);
        h2.put("B", -1);
        h2.put("C", -1);
        h2.put("D", -1);
        h2.put("E", -1);
        h2.put("F", -1);
        h2.put("G", -1);
        h2.put("H", -1);
        h2.put("I", -1);
        h2.put("J", -1);
        h2.put("K", -1);
        h2.put("L", -1);
        h2.put("M", -1);
        h2.put("N", -1);
        h2.put("O", -1);
        h2.put("P", -1);
        h2.put("Q", -1);
        h2.put("R", -1);
        h2.put("S", -1);
        h2.put("T", -1);
        h2.put("U", -1);
        h2.put("V", -1);
        h2.put("X", -1);
        h2.put("W", -1);
        h2.put("Y", -1);
        h2.put("X", -1);
        h2.put("Z", -1);
        h2.put("[", -1);
        h2.put("\'",-1);
        h2.put("]", -1);
        h2.put("^", -1);
        h2.put("_", -1);
        h2.put("`", -1);
        h2.put("a", -1);
        h2.put("b", -1);
        h2.put("c", -1);
        h2.put("d", -1);
        h2.put("e", -1);
        h2.put("f", -1);
        h2.put("g", -1);
        h2.put("h", -1);
        h2.put("i", -1);
        h2.put("j", -1);
        h2.put("k", -1);
        h2.put("l", -1);
        h2.put("m", -1);
        h2.put("n", -1);
        h2.put("o", -1);
        h2.put("p", -1);
        h2.put("q", -1);
        h2.put("r", -1);
        h2.put("s", -1);
        h2.put("t", -1);
        h2.put("u", -1);
        h2.put("v", -1);
        h2.put("w", -1);
        h2.put("x", -1);
        h2.put("y", -1);
        h2.put("z", -1);
        h2.put("{", -1);
        h2.put("|", -1);
        h2.put("}", -1);  
        T.add(h2);
        
        //ESTADO 28 - igual
        h2 = new HashMap();
        h2.put("\t",-1);
        h2.put("\n",-1);
        h2.put("\r",-1);
        h2.put(" ", -1);
        h2.put("!", -1);
        h2.put("\"",-1);
        h2.put("#", -1);
        h2.put("$", -1);
        h2.put("%", -1);
        h2.put("&", -1);
        h2.put("´", -1);
        h2.put("(", -1);
        h2.put(")", -1);
        h2.put("*", -1);
        h2.put("+", -1);
        h2.put(",", -1);
        h2.put("-", -1);
        h2.put(".", -1);
        h2.put("/", -1);
        h2.put("0", -1);
        h2.put("1", -1);
        h2.put("2", -1);
        h2.put("3", -1);
        h2.put("4", -1);
        h2.put("5", -1);
        h2.put("6", -1);
        h2.put("7", -1);
        h2.put("8", -1);
        h2.put("9", -1);
        h2.put(":", -1);
        h2.put(";", -1);
        h2.put("<", -1);
        h2.put("=", -1);
        h2.put(">", -1);
        h2.put("?", -1);
        h2.put("@", -1);
        h2.put("A", -1);
        h2.put("B", -1);
        h2.put("C", -1);
        h2.put("D", -1);
        h2.put("E", -1);
        h2.put("F", -1);
        h2.put("G", -1);
        h2.put("H", -1);
        h2.put("I", -1);
        h2.put("J", -1);
        h2.put("K", -1);
        h2.put("L", -1);
        h2.put("M", -1);
        h2.put("N", -1);
        h2.put("O", -1);
        h2.put("P", -1);
        h2.put("Q", -1);
        h2.put("R", -1);
        h2.put("S", -1);
        h2.put("T", -1);
        h2.put("U", -1);
        h2.put("V", -1);
        h2.put("X", -1);
        h2.put("W", -1);
        h2.put("Y", -1);
        h2.put("X", -1);
        h2.put("Z", -1);
        h2.put("[", -1);
        h2.put("\'",-1);
        h2.put("]", -1);
        h2.put("^", -1);
        h2.put("_", -1);
        h2.put("`", -1);
        h2.put("a", -1);
        h2.put("b", -1);
        h2.put("c", -1);
        h2.put("d", -1);
        h2.put("e", -1);
        h2.put("f", -1);
        h2.put("g", -1);
        h2.put("h", -1);
        h2.put("i", -1);
        h2.put("j", -1);
        h2.put("k", -1);
        h2.put("l", -1);
        h2.put("m", -1);
        h2.put("n", -1);
        h2.put("o", -1);
        h2.put("p", -1);
        h2.put("q", -1);
        h2.put("r", -1);
        h2.put("s", -1);
        h2.put("t", -1);
        h2.put("u", -1);
        h2.put("v", -1);
        h2.put("w", -1);
        h2.put("x", -1);
        h2.put("y", -1);
        h2.put("z", -1);
        h2.put("{", -1);
        h2.put("|", -1);
        h2.put("}", -1);  
        T.add(h2);
        
        //ESTADO 29 - maiorig 
        h2 = new HashMap();
        h2.put("\t",-1);
        h2.put("\n",-1);
        h2.put("\r",-1);
        h2.put(" ", -1);
        h2.put("!", -1);
        h2.put("\"",-1);
        h2.put("#", -1);
        h2.put("$", -1);
        h2.put("%", -1);
        h2.put("&", -1);
        h2.put("´", -1);
        h2.put("(", -1);
        h2.put(")", -1);
        h2.put("*", -1);
        h2.put("+", -1);
        h2.put(",", -1);
        h2.put("-", -1);
        h2.put(".", -1);
        h2.put("/", -1);
        h2.put("0", -1);
        h2.put("1", -1);
        h2.put("2", -1);
        h2.put("3", -1);
        h2.put("4", -1);
        h2.put("5", -1);
        h2.put("6", -1);
        h2.put("7", -1);
        h2.put("8", -1);
        h2.put("9", -1);
        h2.put(":", -1);
        h2.put(";", -1);
        h2.put("<", -1);
        h2.put("=", -1);
        h2.put(">", -1);
        h2.put("?", -1);
        h2.put("@", -1);
        h2.put("A", -1);
        h2.put("B", -1);
        h2.put("C", -1);
        h2.put("D", -1);
        h2.put("E", -1);
        h2.put("F", -1);
        h2.put("G", -1);
        h2.put("H", -1);
        h2.put("I", -1);
        h2.put("J", -1);
        h2.put("K", -1);
        h2.put("L", -1);
        h2.put("M", -1);
        h2.put("N", -1);
        h2.put("O", -1);
        h2.put("P", -1);
        h2.put("Q", -1);
        h2.put("R", -1);
        h2.put("S", -1);
        h2.put("T", -1);
        h2.put("U", -1);
        h2.put("V", -1);
        h2.put("X", -1);
        h2.put("W", -1);
        h2.put("Y", -1);
        h2.put("X", -1);
        h2.put("Z", -1);
        h2.put("[", -1);
        h2.put("\'",-1);
        h2.put("]", -1);
        h2.put("^", -1);
        h2.put("_", -1);
        h2.put("`", -1);
        h2.put("a", -1);
        h2.put("b", -1);
        h2.put("c", -1);
        h2.put("d", -1);
        h2.put("e", -1);
        h2.put("f", -1);
        h2.put("g", -1);
        h2.put("h", -1);
        h2.put("i", -1);
        h2.put("j", -1);
        h2.put("k", -1);
        h2.put("l", -1);
        h2.put("m", -1);
        h2.put("n", -1);
        h2.put("o", -1);
        h2.put("p", -1);
        h2.put("q", -1);
        h2.put("r", -1);
        h2.put("s", -1);
        h2.put("t", -1);
        h2.put("u", -1);
        h2.put("v", -1);
        h2.put("w", -1);
        h2.put("x", -1);
        h2.put("y", -1);
        h2.put("z", -1);
        h2.put("{", -1);
        h2.put("|", -1);
        h2.put("}", -1);  
        T.add(h2);
        
        //ESTADO 30 - ou
        h2 = new HashMap();
        h2.put("\t",-1);
        h2.put("\n",-1);
        h2.put("\r",-1);
        h2.put(" ", -1);
        h2.put("!", -1);
        h2.put("\"",-1);
        h2.put("#", -1);
        h2.put("$", -1);
        h2.put("%", -1);
        h2.put("&", -1);
        h2.put("´", -1);
        h2.put("(", -1);
        h2.put(")", -1);
        h2.put("*", -1);
        h2.put("+", -1);
        h2.put(",", -1);
        h2.put("-", -1);
        h2.put(".", -1);
        h2.put("/", -1);
        h2.put("0", -1);
        h2.put("1", -1);
        h2.put("2", -1);
        h2.put("3", -1);
        h2.put("4", -1);
        h2.put("5", -1);
        h2.put("6", -1);
        h2.put("7", -1);
        h2.put("8", -1);
        h2.put("9", -1);
        h2.put(":", -1);
        h2.put(";", -1);
        h2.put("<", -1);
        h2.put("=", -1);
        h2.put(">", -1);
        h2.put("?", -1);
        h2.put("@", -1);
        h2.put("A", -1);
        h2.put("B", -1);
        h2.put("C", -1);
        h2.put("D", -1);
        h2.put("E", -1);
        h2.put("F", -1);
        h2.put("G", -1);
        h2.put("H", -1);
        h2.put("I", -1);
        h2.put("J", -1);
        h2.put("K", -1);
        h2.put("L", -1);
        h2.put("M", -1);
        h2.put("N", -1);
        h2.put("O", -1);
        h2.put("P", -1);
        h2.put("Q", -1);
        h2.put("R", -1);
        h2.put("S", -1);
        h2.put("T", -1);
        h2.put("U", -1);
        h2.put("V", -1);
        h2.put("X", -1);
        h2.put("W", -1);
        h2.put("Y", -1);
        h2.put("X", -1);
        h2.put("Z", -1);
        h2.put("[", -1);
        h2.put("\'",-1);
        h2.put("]", -1);
        h2.put("^", -1);
        h2.put("_", -1);
        h2.put("`", -1);
        h2.put("a", -1);
        h2.put("b", -1);
        h2.put("c", -1);
        h2.put("d", -1);
        h2.put("e", -1);
        h2.put("f", -1);
        h2.put("g", -1);
        h2.put("h", -1);
        h2.put("i", -1);
        h2.put("j", -1);
        h2.put("k", -1);
        h2.put("l", -1);
        h2.put("m", -1);
        h2.put("n", -1);
        h2.put("o", -1);
        h2.put("p", -1);
        h2.put("q", -1);
        h2.put("r", -1);
        h2.put("s", -1);
        h2.put("t", -1);
        h2.put("u", -1);
        h2.put("v", -1);
        h2.put("w", -1);
        h2.put("x", -1);
        h2.put("y", -1);
        h2.put("z", -1);
        h2.put("{", -1);
        h2.put("|", -1);
        h2.put("}", -1);  
        T.add(h2);
        
        //ESTADO 
        h2 = new HashMap();
        h2.put("\t",-1);
        h2.put("\n",-1);
        h2.put("\r",-1);
        h2.put(" ", -1);
        h2.put("!", -1);
        h2.put("\"",-1);
        h2.put("#", -1);
        h2.put("$", -1);
        h2.put("%", -1);
        h2.put("&", -1);
        h2.put("´", -1);
        h2.put("(", -1);
        h2.put(")", -1);
        h2.put("*", -1);
        h2.put("+", -1);
        h2.put(",", -1);
        h2.put("-", -1);
        h2.put(".", -1);
        h2.put("/", -1);
        h2.put("0", -1);
        h2.put("1", -1);
        h2.put("2", -1);
        h2.put("3", -1);
        h2.put("4", -1);
        h2.put("5", -1);
        h2.put("6", -1);
        h2.put("7", -1);
        h2.put("8", -1);
        h2.put("9", -1);
        h2.put(":", -1);
        h2.put(";", -1);
        h2.put("<", -1);
        h2.put("=", -1);
        h2.put(">", -1);
        h2.put("?", -1);
        h2.put("@", -1);
        h2.put("A", -1);
        h2.put("B", -1);
        h2.put("C", -1);
        h2.put("D", -1);
        h2.put("E", -1);
        h2.put("F", -1);
        h2.put("G", -1);
        h2.put("H", -1);
        h2.put("I", -1);
        h2.put("J", -1);
        h2.put("K", -1);
        h2.put("L", -1);
        h2.put("M", -1);
        h2.put("N", -1);
        h2.put("O", -1);
        h2.put("P", -1);
        h2.put("Q", -1);
        h2.put("R", -1);
        h2.put("S", -1);
        h2.put("T", -1);
        h2.put("U", -1);
        h2.put("V", -1);
        h2.put("X", -1);
        h2.put("W", -1);
        h2.put("Y", -1);
        h2.put("X", -1);
        h2.put("Z", -1);
        h2.put("[", -1);
        h2.put("\'",-1);
        h2.put("]", -1);
        h2.put("^", -1);
        h2.put("_", -1);
        h2.put("`", -1);
        h2.put("a", -1);
        h2.put("b", -1);
        h2.put("c", -1);
        h2.put("d", -1);
        h2.put("e", -1);
        h2.put("f", -1);
        h2.put("g", -1);
        h2.put("h", -1);
        h2.put("i", -1);
        h2.put("j", -1);
        h2.put("k", -1);
        h2.put("l", -1);
        h2.put("m", -1);
        h2.put("n", -1);
        h2.put("o", -1);
        h2.put("p", -1);
        h2.put("q", -1);
        h2.put("r", -1);
        h2.put("s", -1);
        h2.put("t", -1);
        h2.put("u", -1);
        h2.put("v", -1);
        h2.put("w", -1);
        h2.put("x", -1);
        h2.put("y", -1);
        h2.put("z", -1);
        h2.put("{", -1);
        h2.put("|", -1);
        h2.put("}", -1);  
        T.add(h2);
        
        //ESTADO 31 - real
        h2 = new HashMap();
        h2.put("\t",-1);
        h2.put("\n",-1);
        h2.put("\r",-1);
        h2.put(" ", -1);
        h2.put("!", -1);
        h2.put("\"",-1);
        h2.put("#", -1);
        h2.put("$", -1);
        h2.put("%", -1);
        h2.put("&", -1);
        h2.put("´", -1);
        h2.put("(", -1);
        h2.put(")", -1);
        h2.put("*", -1);
        h2.put("+", -1);
        h2.put(",", -1);
        h2.put("-", -1);
        h2.put(".", -1);
        h2.put("/", -1);
        h2.put("0", 32);
        h2.put("1", 32);
        h2.put("2", 32);
        h2.put("3", 32);
        h2.put("4", 32);
        h2.put("5", 32);
        h2.put("6", 32);
        h2.put("7", 32);
        h2.put("8", 32);
        h2.put("9", 32);
        h2.put(":", -1);
        h2.put(";", -1);
        h2.put("<", -1);
        h2.put("=", -1);
        h2.put(">", -1);
        h2.put("?", -1);
        h2.put("@", -1);
        h2.put("A", -1);
        h2.put("B", -1);
        h2.put("C", -1);
        h2.put("D", -1);
        h2.put("E", -1);
        h2.put("F", -1);
        h2.put("G", -1);
        h2.put("H", -1);
        h2.put("I", -1);
        h2.put("J", -1);
        h2.put("K", -1);
        h2.put("L", -1);
        h2.put("M", -1);
        h2.put("N", -1);
        h2.put("O", -1);
        h2.put("P", -1);
        h2.put("Q", -1);
        h2.put("R", -1);
        h2.put("S", -1);
        h2.put("T", -1);
        h2.put("U", -1);
        h2.put("V", -1);
        h2.put("X", -1);
        h2.put("W", -1);
        h2.put("Y", -1);
        h2.put("X", -1);
        h2.put("Z", -1);
        h2.put("[", -1);
        h2.put("\'",-1);
        h2.put("]", -1);
        h2.put("^", -1);
        h2.put("_", -1);
        h2.put("`", -1);
        h2.put("a", -1);
        h2.put("b", -1);
        h2.put("c", -1);
        h2.put("d", -1);
        h2.put("e", -1);
        h2.put("f", -1);
        h2.put("g", -1);
        h2.put("h", -1);
        h2.put("i", -1);
        h2.put("j", -1);
        h2.put("k", -1);
        h2.put("l", -1);
        h2.put("m", -1);
        h2.put("n", -1);
        h2.put("o", -1);
        h2.put("p", -1);
        h2.put("q", -1);
        h2.put("r", -1);
        h2.put("s", -1);
        h2.put("t", -1);
        h2.put("u", -1);
        h2.put("v", -1);
        h2.put("w", -1);
        h2.put("x", -1);
        h2.put("y", -1);
        h2.put("z", -1);
        h2.put("{", -1);
        h2.put("|", -1);
        h2.put("}", -1);  
        T.add(h2);
        
        //ESTADO 32 - const
        h2 = new HashMap();
        h2.put("\t",-1);
        h2.put("\n",-1);
        h2.put("\r",-1);
        h2.put(" ", -1);
        h2.put("!", -1);
        h2.put("\"",-1);
        h2.put("#", -1);
        h2.put("$", -1);
        h2.put("%", -1);
        h2.put("&", -1);
        h2.put("´", -1);
        h2.put("(", -1);
        h2.put(")", -1);
        h2.put("*", -1);
        h2.put("+", -1);
        h2.put(",", -1);
        h2.put("-", -1);
        h2.put(".", -1);
        h2.put("/", -1);
        h2.put("0", 32);
        h2.put("1", 32);
        h2.put("2", 32);
        h2.put("3", 32);
        h2.put("4", 32);
        h2.put("5", 32);
        h2.put("6", 32);
        h2.put("7", 32);
        h2.put("8", 32);
        h2.put("9", 32);
        h2.put(":", -1);
        h2.put(";", -1);
        h2.put("<", -1);
        h2.put("=", -1);
        h2.put(">", -1);
        h2.put("?", -1);
        h2.put("@", -1);
        h2.put("A", -1);
        h2.put("B", -1);
        h2.put("C", -1);
        h2.put("D", -1);
        h2.put("E", -1);
        h2.put("F", -1);
        h2.put("G", -1);
        h2.put("H", -1);
        h2.put("I", -1);
        h2.put("J", -1);
        h2.put("K", -1);
        h2.put("L", -1);
        h2.put("M", -1);
        h2.put("N", -1);
        h2.put("O", -1);
        h2.put("P", -1);
        h2.put("Q", -1);
        h2.put("R", -1);
        h2.put("S", -1);
        h2.put("T", -1);
        h2.put("U", -1);
        h2.put("V", -1);
        h2.put("X", -1);
        h2.put("W", -1);
        h2.put("Y", -1);
        h2.put("X", -1);
        h2.put("Z", -1);
        h2.put("[", -1);
        h2.put("\'",-1);
        h2.put("]", -1);
        h2.put("^", -1);
        h2.put("_", -1);
        h2.put("`", -1);
        h2.put("a", -1);
        h2.put("b", -1);
        h2.put("c", -1);
        h2.put("d", -1);
        h2.put("e", -1);
        h2.put("f", -1);
        h2.put("g", -1);
        h2.put("h", -1);
        h2.put("i", -1);
        h2.put("j", -1);
        h2.put("k", -1);
        h2.put("l", -1);
        h2.put("m", -1);
        h2.put("n", -1);
        h2.put("o", -1);
        h2.put("p", -1);
        h2.put("q", -1);
        h2.put("r", -1);
        h2.put("s", -1);
        h2.put("t", -1);
        h2.put("u", -1);
        h2.put("v", -1);
        h2.put("w", -1);
        h2.put("x", -1);
        h2.put("y", -1);
        h2.put("z", -1);
        h2.put("{", -1);
        h2.put("|", -1);
        h2.put("}", -1);  
        T.add(h2);
        
    }
  
    public void constroiTabelaTokens(){
        
        ts.put(0, "?");
        ts.put(1, "espaco");
        ts.put(2, "not");
        ts.put(3, "?");
        ts.put(4, "ap");
        ts.put(5, "fp");
        ts.put(6, "mult");
        ts.put(7, "soma");
        ts.put(8, "v");
        ts.put(9, "subt");
        ts.put(10, "div");
        ts.put(11, "const");
        ts.put(12, "dp");
        ts.put(13, "pv");
        ts.put(14, "menor");
        ts.put(15, "at");
        ts.put(16, "maior");
        ts.put(17, "id");
        ts.put(18, "ac");
        ts.put(19, "?");
        ts.put(20, "fc");
        ts.put(21, "e");
        ts.put(22, "inc");
        ts.put(23, "dec");
        ts.put(24, "?");
        ts.put(25, "const");
        ts.put(26, "menorig");
        ts.put(27, "dif");
        ts.put(28, "igual");
        ts.put(29, "maiorig");
        ts.put(30, "ou");
        ts.put(31, "real");
        ts.put(32, "const");
        
    }
    
    public void palavrasReservadas(){
        
        pReservada.put("if", "if");
        pReservada.put("then", "then");
        pReservada.put("else", "else");
        pReservada.put("while", "while");
        pReservada.put("begin", "begin");
        pReservada.put("end", "end");
        pReservada.put("for", "for");
        pReservada.put("int", "int");
        pReservada.put("str", "str");
        pReservada.put("double", "double");
        pReservada.put("boolean", "boolean");
        pReservada.put("float", "float");
    }
       
}

